### ISSUE TITLE
Exception when using proguard on android

### ISSUE THREAD

**Issue by marinat** [xerial/sqlite-jdbc#1048]
When I use proguard I get:
```
thread.cc:2519] No pending exception expected: java.lang.NoSuchFieldError: no "J" field "pointer" in class "Lorg/sqlite/core/NativeDB;" or its superclasses
                                                                                                    thread.cc:2519]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class) (Runtime.java:-2)
                                                                                                    thread.cc:2519]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1126)
                                                                                                    thread.cc:2519]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1080)
                                                                                                    thread.cc:2519]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:1003)
                                                                                                    thread.cc:2519]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1661)
                                                                                                    thread.cc:2519]   at void org.sqlite.core.NativeDB.<clinit>() (SourceFile:-1)
                                                                                                    thread.cc:2519]   at org.sqlite.core.NativeDB org.sqlite.SQLiteConnection.open(java.lang.String, java.lang.String, java.util.Properties) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void org.sqlite.SQLiteConnection.<init>(java.lang.String, java.lang.String, java.util.Properties) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void org.sqlite.jdbc3.JDBC3Connection.<init>(java.lang.String, java.lang.String, java.util.Properties) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at java.sql.Connection org.sqlite.JDBC.connect(java.lang.String, java.util.Properties) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at java.sql.Connection java.sql.DriverManager.getConnection(java.lang.String, java.util.Properties, java.lang.Class) (DriverManager.java:580)
                                                                                                    thread.cc:2519]   at java.sql.Connection java.sql.DriverManager.getConnection(java.lang.String, java.lang.String, java.lang.String) (DriverManager.java:218)
                                                                                                    thread.cc:2519]   at void app.spotter.data.db.DatabaseController.openDatabase(char[]) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke() (SourceFile:174)
                                                                                                    thread.cc:2519]   at java.lang.Object androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke() (SourceFile:10)
                                                                                                    thread.cc:2519]   at void okhttp3.Handshake$peerCertificates$2.invoke() (SourceFile:7)
                                                                                                    thread.cc:2519]   at java.lang.Object okhttp3.Handshake$peerCertificates$2.invoke() (SourceFile:18)
                                                                                                    thread.cc:2519]   at java.lang.Object androidx.compose.ui.node.NodeChainKt$fillVector$1.invoke(java.lang.Object) (SourceFile:134)
                                                                                                    thread.cc:2519]   at java.lang.Object androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(java.lang.Object) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(java.lang.Object) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void kotlin.time.DurationKt.resume(kotlinx.coroutines.DispatchedTask, kotlin.coroutines.Continuation, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(int) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(java.lang.Object, int, kotlin.jvm.functions.Function1) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void kotlinx.coroutines.CancellableContinuationImpl.resumeWith(java.lang.Object) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(androidx.compose.ui.input.pointer.PointerEvent, androidx.compose.ui.input.pointer.PointerEventPass) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(androidx.compose.ui.input.pointer.PointerEvent, androidx.compose.ui.input.pointer.PointerEventPass, long) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at void androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(androidx.compose.ui.input.pointer.PointerEvent, androidx.compose.ui.input.pointer.PointerEventPass, long) (SourceFile:-1)
2024-01-09 11:42:41.983 23202-23202 app.spotter             app.spotter                          A  thread.cc:2519]   at void androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(androidx.compose.ui.input.pointer.PointerEvent, androidx.compose.ui.input.pointer.PointerEventPass, long) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(java.util.Map, androidx.compose.ui.layout.LayoutCoordinates, com.google.android.gms.tasks.zzr, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(java.util.Map, androidx.compose.ui.layout.LayoutCoordinates, com.google.android.gms.tasks.zzr, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(java.util.Map, androidx.compose.ui.layout.LayoutCoordinates, com.google.android.gms.tasks.zzr, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(java.util.Map, androidx.compose.ui.layout.LayoutCoordinates, com.google.android.gms.tasks.zzr, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(java.util.Map, androidx.compose.ui.layout.LayoutCoordinates, com.google.android.gms.tasks.zzr, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.work.impl.StartStopTokens.dispatchChanges(com.google.android.gms.tasks.zzr, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at int androidx.emoji2.text.EmojiProcessor.process-BIzXfog(androidx.compose.ui.input.pointer.PointerInputEvent, androidx.compose.ui.input.pointer.PositionCalculator, boolean) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at int androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(android.view.MotionEvent) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at int androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(android.view.MotionEvent) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(android.view.MotionEvent) (SourceFile:-1)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTransformedTouchEvent(android.view.MotionEvent, boolean, android.view.View, int) (ViewGroup.java:3120)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTouchEvent(android.view.MotionEvent) (ViewGroup.java:2801)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTransformedTouchEvent(android.view.MotionEvent, boolean, android.view.View, int) (ViewGroup.java:3120)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTouchEvent(android.view.MotionEvent) (ViewGroup.java:2801)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTransformedTouchEvent(android.view.MotionEvent, boolean, android.view.View, int) (ViewGroup.java:3120)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTouchEvent(android.view.MotionEvent) (ViewGroup.java:2801)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTransformedTouchEvent(android.view.MotionEvent, boolean, android.view.View, int) (ViewGroup.java:3120)
                                                                                                    thread.cc:2519]   at boolean android.view.ViewGroup.dispatchTouchEvent(android.view.MotionEvent) (ViewGroup.java:2801)
                                                                                                    thread.cc:2519]   at boolean com.android.internal.policy.DecorView.superDispatchTouchEvent(android.view.MotionEvent) (DecorView.java:490)
                                                                                                    thread.cc:2519]   at boolean com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(android.view.MotionEvent) (PhoneWindow.java:1904)
                                                                                                    thread.cc:2519]   at boolean android.app.Activity.dispatchTouchEvent(android.view.MotionEvent) (Activity.java:4377)
                                                                                                    thread.cc:2519]   at boolean com.android.internal.policy.DecorView.dispatchTouchEvent(android.view.MotionEvent) (DecorView.java:448)
                                                                                                    thread.cc:2519]   at boolean android.view.View.dispatchPointerEvent(android.view.MotionEvent) (View.java:15919)
                                                                                                    thread.cc:2519]   at int android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:7021)
2024-01-09 11:42:41.983 23202-23202 app.spotter             app.spotter                          A  thread.cc:2519]   at int android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6815)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6229)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6286)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6252)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$AsyncInputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6417)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:6260)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$AsyncInputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:6474)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6233)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.onDeliverToNext(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6286)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.forward(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6252)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.apply(android.view.ViewRootImpl$QueuedInputEvent, int) (ViewRootImpl.java:6260)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$InputStage.deliver(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:6233)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl.deliverInputEvent(android.view.ViewRootImpl$QueuedInputEvent) (ViewRootImpl.java:9211)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl.doProcessInputEvents() (ViewRootImpl.java:9162)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl.enqueueInputEvent(android.view.InputEvent, android.view.InputEventReceiver, int, boolean) (ViewRootImpl.java:9131)
                                                                                                    thread.cc:2519]   at void android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(android.view.InputEvent) (ViewRootImpl.java:9337)
                                                                                                    thread.cc:2519]   at void android.view.InputEventReceiver.dispatchInputEvent(int, android.view.InputEvent) (InputEventReceiver.java:267)
                                                                                                    thread.cc:2519]   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
                                                                                                    thread.cc:2519]   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:335)
                                                                                                    thread.cc:2519]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:162)
                                                                                                    thread.cc:2519]   at void android.os.Looper.loop() (Looper.java:294)
                                                                                                    thread.cc:2519]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8177)
                                                                                                    thread.cc:2519]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                    thread.cc:2519]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:552)
                                                                                                    thread.cc:2519]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:971)
                                                                                                    thread.cc:2519] 
2024-01-09 11:42:42.148 23202-23202 app.spotter             app.spotter                          A  runtime.cc:691] Runtime aborting...
                                                                                                    runtime.cc:691] All threads:
                                                                                                    runtime.cc:691] DALVIK THREADS (21):
                                                                                                    runtime.cc:691] "main" prio=10 tid=1 Runnable
                                                                                                    runtime.cc:691]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x72320478 self=0xb40000793858d380
                                                                                                    runtime.cc:691]   | sysTid=23202 nice=-10 cgrp=system sched=0/0 handle=0x7bc729f4f8
                                                                                                    runtime.cc:691]   | state=R schedstat=( 2923260350 1160495316 2736 ) utm=255 stm=36 core=7 HZ=100
                                                                                                    runtime.cc:691]   | stack=0x7ffc993000-0x7ffc995000 stackSize=8188KB
                                                                                                    runtime.cc:691]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:691]   native: #00 pc 004bca80  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack+108) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #01 pc 004b0dd4  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack const+388) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #02 pc 004b0714  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run+164) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #03 pc 003ada50  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint+452) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #04 pc 004c99bc  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump+232) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #05 pc 00771fe4  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort+2156) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #06 pc 000357d0  /apex/com.google.mainline.primary.libs@341177000/lib64/libbase.so/75d3253827fcfd7a8d7b02ad45991611ec4ca424c0278e13e8acfad4d14e597a3ecff6c0caa2b785c73838528ee6e9c2b313240ff895f50ee39b1d7bc10f390a/libbase.so (android::base::SetAborter::$_0::__invoke+80) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
                                                                                                    runtime.cc:691]   native: #07 pc 00034d58  /apex/com.google.mainline.primary.libs@341177000/lib64/libbase.so/75d3253827fcfd7a8d7b02ad45991611ec4ca424c0278e13e8acfad4d14e597a3ecff6c0caa2b785c73838528ee6e9c2b313240ff895f50ee39b1d7bc10f390a/libbase.so (android::base::LogMessage::~LogMessage+352) (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
                                                                                                    runtime.cc:691]   native: #08 pc 002585cc  /apex/com.android.art/lib64/libart.so (art::ClassLinker::FindClass+10444) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #09 pc 00553bd8  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass+696) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #10 pc 00045464  /data/app/~~LcC0oPRqEl9-Ofa9aLrxUA==/app.spotter-d2QePnpv6Rl4q8aWiVf1JA==/base.apk (offset d40000) (JNI_OnLoad+672)
                                                                                                    runtime.cc:691]   native: #11 pc 0051a7d4  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary+1872) (BuildId: 735f12f804f88d62a2cb437261076ff7)
                                                                                                    runtime.cc:691]   native: #12 pc 000051c0  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+412) (BuildId: e2d871bce04eabb6198cc5c94b2b4059)
                                                                                                    runtime.cc:691]   at java.lang.Runtime.nativeLoad(Native method)
                                                                                                    runtime.cc:691]   at java.lang.Runtime.nativeLoad(Runtime.java:1126)
                                                                                                    runtime.cc:691]   at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
                                                                                                    runtime.cc:691]   - locked <0x02fe6aae> (a java.lang.Runtime)
                                                                                                    runtime.cc:691]   at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    runtime.cc:691]   at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    runtime.cc:691]   at org.sqlite.core.NativeDB.<clinit>(unavailable:24)
                                                                                                    runtime.cc:691]   at org.sqlite.SQLiteConnection.open(unavailable:489)
                                                                                                    runtime.cc:691]   at org.sqlite.SQLiteConnection.<init>(unavailable:9)
                                                                                                    runtime.cc:691]   at org.sqlite.jdbc3.JDBC3Connection.<init>(unavailable:0)
                                                                                                    runtime.cc:691]   at org.sqlite.JDBC.connect(unavailable:26)
                                                                                                    runtime.cc:691]   at java.sql.DriverManager.getConnection(DriverManager.java:580)
                                                                                                    runtime.cc:691]   at java.sql.DriverManager.getConnection(DriverManager.java:218)
                                                                                                    runtime.cc:691]   at app.spotter.data.db.DatabaseController.openDatabase(unavailable:25)
2024-01-09 11:42:42.148 23202-23202 app.spotter             app.spotter                          A  runtime.cc:691]   at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(SourceFile:174)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(SourceFile:10)
                                                                                                    runtime.cc:691]   at okhttp3.Handshake$peerCertificates$2.invoke(SourceFile:7)
                                                                                                    runtime.cc:691]   at okhttp3.Handshake$peerCertificates$2.invoke(SourceFile:18)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.node.NodeChainKt$fillVector$1.invoke(SourceFile:134)
                                                                                                    runtime.cc:691]   at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(unavailable:133)
                                                                                                    runtime.cc:691]   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(unavailable:7)
                                                                                                    runtime.cc:691]   at kotlin.time.DurationKt.resume(unavailable:78)
                                                                                                    runtime.cc:691]   at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(unavailable:99)
                                                                                                    runtime.cc:691]   at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(unavailable:32)
                                                                                                    runtime.cc:691]   at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(unavailable:16)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(unavailable:50)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(unavailable:30)
                                                                                                    runtime.cc:691]   at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(unavailable:4)
                                                                                                    runtime.cc:691]   at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(unavailable:4)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(unavailable:170)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(unavailable:149)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(unavailable:149)
                                                                                                    runtime.cc:691]   ... repeated 0 times
                                                                                                    runtime.cc:691]   at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(unavailable:25)
                                                                                                    runtime.cc:691]   at androidx.work.impl.StartStopTokens.dispatchChanges(unavailable:28)
                                                                                                    runtime.cc:691]   at androidx.emoji2.text.EmojiProcessor.process-BIzXfog(unavailable:186)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(unavailable:80)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(unavailable:213)
                                                                                                    runtime.cc:691]   at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(unavailable:80)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                                                                                    runtime.cc:691]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                                                                                    runtime.cc:691]   at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
                                                                                                    runtime.cc:691]   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
                                                                                                    runtime.cc:691]   at android.app.Activity.dispatchTouchEvent(Activity.java:4377)
                                                                                                    runtime.cc:691]   at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
                                                                                                    runtime.cc:691]   at android.view.View.dispatchPointerEvent(View.java:15919)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7021)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6815)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
2024-01-09 11:42:42.148 23202-23202 app.spotter             app.spotter                          A  runtime.cc:691]   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9211)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9162)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9131)
                                                                                                    runtime.cc:691]   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9337)
                                                                                                    runtime.cc:691]   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
                                                                                                    runtime.cc:691]   at android.os.MessageQueue.nativePollOnce(Native method)
                                                                                                    runtime.cc:691]   at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    runtime.cc:691]   at android.os.Looper.loopOnce(Looper.java:162)
                                                                                                    runtime.cc:691]   at android.os.Looper.loop(Looper.java:294)
                                                                                                    runtime.cc:691]   at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    runtime.cc:691]   at java.lang.reflect.Method.invoke(Native method)
                                                                                                    runtime.cc:691]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    runtime.cc:691]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    runtime.cc:691]
```

Proguard rules:
```
-keep class org.sqlite.**
-keep class java.sql.**
-dontwarn java.sql.JDBCType
```

Mac os Sonoma 14.0, min android sdk 34

**Comment by marinat** [comment]
for all interested just use rules:
```-keep class org.sqlite.** { *; }
-keep class java.sql.** { *; }
-keep class app.spotter.data.**
-keep class org.sqlite.core.NativeDB { long pointer; }

-dontwarn java.sql.JDBCType```
