### ISSUE TITLE
put might be a setProperty

### ISSUE THREAD

**Issue by stbischof** [xerial/sqlite-jdbc#1196]
https://github.com/xerial/sqlite-jdbc/blob/fd210583a0540c2c881a4f3e4d672653dcf3a2c7/src/main/java/org/sqlite/SQLiteConfig.java#L310

```
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1346)
	at org.sqlite.SQLiteConfig.setPragma(SQLiteConfig.java:310)
```

**Comment by gotson** [comment]
please add some context and description

**Comment by stbischof** [comment]
I used setpragma to set a Password and got i nullpointer excepttion.

I think it is because you used properies.put.

In all other cases u use setProperty

**Comment by gotson** [comment]
can you provide a repro ?
