### ISSUE TITLE
slf4j/LoggerFactory: ClassNotFoundException [3.47.1.0]

### ISSUE THREAD

**Issue by BLCK-B** [xerial/sqlite-jdbc#1222]
**Describe the bug**
Latest version 3.47.1.0 causes an exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.apache.logging.slf4j.SLF4JLoggerContext.createLogger(SLF4JLoggerContext.java:57)
	at org.apache.logging.slf4j.SLF4JLoggerContext.getLogger(SLF4JLoggerContext.java:51)
	at org.apache.logging.slf4j.SLF4JLoggerContext.getLogger(SLF4JLoggerContext.java:40)
	at org.apache.commons.logging.LogAdapter$Log4jLog.<init>(LogAdapter.java:159)
	at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:113)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:95)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at spring.boot@3.4.1/org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:202)
	at issueRepro.main/org.blck.issuerepro.Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 10 more
```

**To Reproduce**

`git clone https://github.com/BLCK-B/sqliteSLF4Jissue`

I just run Main using green arrow in IntelliJ IDEA. `bootRun` does not trigger this issue.

You can toggle sqlite version in `build.gradle`.

**Environment (please complete the following information):**
- VM: GraalVM 24.02 - Java 22.02
 - sqlite-jdbc version 3.47.1.0

**Additional context**
https://github.com/xerial/sqlite-jdbc/commit/81b05ec5c216f0976c98fc9e8fcc52ac7388cfe3

**Comment by neoxpert** [comment]
While slf4j should be optional, have you tried adding the slf4j-api to your project or a suitable substitute for your logging framework of choice (if used)?

**Comment by gotson** [comment]
Doesn't Spring Boot uses SLF4J by default ?

**Comment by neoxpert** [comment]
Yes it does. As the bootRun task is working (just ran it on my setup), I would say it's an issue within the project setup / IDE but not sqlite-jdbc itself. In the current state, also Eclipse does not properly setup the module path when running Main directly.

**Comment by gotson** [comment]
seems indeed like an IDE issue, thus i am closing this.
