### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by m3920752** [xerial/sqlite-jdbc#138]
I build on ubuntu x64 and generate "sqlite-jdbc-3.13.0-SNAPSHOT.jar", then
I run "BackupTest.java" on windows7 x64, it's OK. BUT i failed to run "BusyHandlerTest.java":

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB.busy_handler(Lorg/sqlite/BusyHandler;)V
	at org.sqlite.core.NativeDB.busy_handler(Native Method)
	at org.sqlite.BusyHandler.commitHandler(BusyHandler.java:30)
	at org.sqlite.BusyHandler.setHandler(BusyHandler.java:41)
	at org.sqlite.BusyHandlerTest.basicBusyHandler(BusyHandlerTest.java:92)
	at org.sqlite.BusyHandlerTest.main(BusyHandlerTest.java:85)

**Comment by gitblit** [comment]
We have not yet built the native binaries for 3.13.0.
>
>

**Comment by m3920752** [comment]
Thank you so much. When the binaries for 3.13.0 will be ok ?

**Comment by gitblit** [comment]
We're not sure when the 3.13.0 binaries will be available.
