### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by GKLuke** [xerial/sqlite-jdbc#141]
`Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
        at org.sqlite.core.NativeDB._open(Native Method)
        at org.sqlite.core.DB.open(DB.java:161)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at SQLiteJDBC.main(SQLiteJDBC.java:11)
`
 I use  **a raspberry pi 3**, OS  raspbian (based on Debian 8 jessie), jdk and java VM below 
![qq 20160813123130](https://cloud.githubusercontent.com/assets/8219798/17641430/e45910c6-6151-11e6-8fb4-2367fa579b13.jpg)
Also tested openjdk8, and failed.Cry
I use **sqlite-jdbc-3.8.11.2.jar**.I tested this jar on my Mac(use jdk 1.7) and Windows(also use jdk 1.7), it worked fine.
my test code below

import java.sql.*;
public class SQLiteJDBC
{
  public static void main( String args[] )
  {
    Connection con = null;
    try {
      Class.forName("org.sqlite.JDBC");
      con = DriverManager.getConnection("jdbc:sqlite:/home/pi/Documents/arp.db");
    } catch ( Exception e ) {
      System.err.println( e.getClass().getName() + ": " + e.getMessage() );
      System.exit(0);
    }
    System.out.println("Opened database successfully");
  }
}
 What can I do next?

**Comment by kwantumWare** [comment]
I'm having the same problem, but I'm using a Raspberry Pi vB+.

**Comment by ideniden** [comment]
I'm having the same problem...Also used  Raspbian PI 3

**Comment by omatei01** [comment]
on Pi3 model B, it works with 3.8.10.2.. for me, at least

**Comment by kwantumWare** [comment]
@ideniden Have a look at https://github.com/xerial/sqlite-jdbc/issues/58 . You need to use a patched version of the library. Download here: https://mega.nz/#!RVlylBQL!w6ifnhXdtv6gqMtxLwEXBQjGJqQCsHIRnf1oZsafjdw

**Comment by ideniden** [comment]
@kwantumWare Thanks very mach,Problem has been solved.^-^

**Comment by xerial** [comment]
Could you try the binary I built here?
https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.14.2-SNAPSHOT/

I'm using docker for building Raspberry Pi binary #151

**Comment by xerial** [comment]
Let me merge this issue to #58
