### ISSUE TITLE
 Error opening connection for jdbc:couchbase://127.0.0.1/8091 exception Error getting cluster response

### ISSUE THREAD

**Issue by jayashreeb081767** [xerial/sqlite-jdbc#180]
please help to solve this

00:59:21.389 [main] ERROR com.couchbase.jdbc.core.ProtocolImpl [ProtocolImpl.java:983] - Error opening connection null
00:59:21.401 [main] ERROR com.couchbase.jdbc.CBConnection [CBConnection.java:78] - Error opening connection for jdbc:couchbase://127.0.0.1/8091 exception Error getting cluster response
Exception in thread "main" java.sql.SQLException: Error opening connection
	at com.couchbase.jdbc.CBConnection.<init>(CBConnection.java:79)
	at com.couchbase.jdbc.CBDriver.connect(CBDriver.java:94)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at ca.uhn.fhir.jpa.demo.RetriveDataUsingCouchBase.main(RetriveDataUsingCouchBase.java:18)
Caused by: java.lang.NullPointerException
	at org.boon.json.implementation.JsonParserLax.parse(JsonParserLax.java:287)
	at org.boon.json.implementation.BaseJsonParser.parse(BaseJsonParser.java:127)
	at org.boon.json.implementation.BaseJsonParserAndMapper.parse(BaseJsonParserAndMapper.java:765)
	at org.boon.json.JsonMappingParser.parse(JsonMappingParser.java:699)
	at org.boon.json.implementation.ObjectMapperImpl.fromJson(ObjectMapperImpl.java:303)
	at com.couchbase.jdbc.core.ProtocolImpl.handleClusterResponse(ProtocolImpl.java:284)
	at com.couchbase.jdbc.core.ProtocolImpl.pollCluster(ProtocolImpl.java:979)
	at com.couchbase.jdbc.core.ProtocolImpl.connect(ProtocolImpl.java:238)
	at com.couchbase.jdbc.CBConnection.<init>(CBConnection.java:73)

**Comment by danielcompton** [comment]
I don't think this has anything to do with SQLite and can be closed?

**Comment by gitblit** [comment]
Agreed.  @jayashreeb081767 I think you should follow up with Couchbase.
