### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

### ISSUE THREAD

**Issue by zurausa** [xerial/sqlite-jdbc#225]
I'm still getting this error with latest (3.16.1) version on linux server when excute jar-file using sqlite-jdbc
 in parallel.
It occurred after 3.15.0, but it didn't  occur before 3.14
And it occurred on linux, but it didn't occur on windows.

java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:71)
        at org.sqlite.core.DB.open(DB.java:174)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)

**Comment by tt-jeremye** [comment]
I'm also encountering this problem with 3.16.1 on Linux (amd64). It may be relevant that I'm using this library from a Spark job which creates multiple threads per worker.

**Comment by tt-jeremye** [comment]
This stopped being a problem with my Spark job after I only allowed a single SQLite JDBC connection per JVM, so it does seem likely that it's a threading issue.

**Comment by Sitmobedaf** [comment]
I have the same problem. I see that the SQLite driver is partially inactive.
One developer seems to have fixed this. Dev, you just need to merge the changes and release a new stable.
https://github.com/niktsar/sqlite-jdbc/commit/69a5741c7cb6e2e3cd5e21f6bd748b7323ffce32

**Comment by jouj89** [comment]
Hello, 
I downloaded and compiled sqlite-snapshot-201710041413.tar.gz for SunOs x86_64 , in 64-bits
and I'm using the latest jar sqlite-jdc-3.20.1.jar

I'm facing this error. I also tried to change tmpdir but it's still the same.

java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:71)
        at org.sqlite.core.DB.open(DB.java:174)

groovy -cp sqlite-jdbc-3.20.1.jar -Dorg.sqlite.lib.path="<path>/out_64/lib/" -Dorg.sqlite.lib.name="libsqlite3.so.0.8.6" sql_test.groovy

Any chance this OS is supported and I'm missing a step ?
Many thanks,
Georges

**Comment by eliasbousarkis** [comment]
Hi guys,
We faced the same issue with sqlite 3.27.2.1.
The highest working version on our OS is 3.14.2.1.

**Error:**
Failed to load native library:sqlite-3.27.2.1-091a6e58-65b9-4809-bc2f-36da7a8d80e2-libsqlitejdbc.so. osinfo: Linux/armv7
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.27.2.1-091a6e58-65b9-4809-bc2f-36da7a8d80e2-libsqlitejdbc.so: /tmp/sqlite-3.27.2.1-091a6e58-65b9-4809-bc2f-36da7a8d80e2-libsqlitejdbc.so: cannot open shared object file: No such file or directory
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:78)
        at org.sqlite.core.DB.open(DB.java:195)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at com.activeid.test.sqlite.emissary.Main.main(Main.java:43)


**OS Info:**
java -version
--------------
java version "1.8.0_121"
Java(TM) SE Embedded Runtime Environment (build 1.8.0_121-b13, headless)
Java HotSpot(TM) Embedded Client VM (build 25.121-b13, mixed mode)

uname -a
------------
Linux  #8 SMP PREEMPT Fri Jul 24 11:07:52 PDT 2015 armv7l GNU/Linux

cat /etc/issue
--------------
Debian GNU/Linux 7 \n \l

cat /proc/cpuinfo
----------------------
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Xilinx Zynq Platform
Revision        : 0003
Serial          : 0000000000000000

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.
