### ISSUE TITLE
Can not connect using jdbc:sqlite::resource:

### ISSUE THREAD

**Issue by feimengwang** [xerial/sqlite-jdbc#234]
ERROR: com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:sqlite::resource:youhui.db, errorCode 0, state null
java.sql.SQLException: The prepared statement has been finalized
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.step(Native Method)
	at org.sqlite.core.DB.execute(DB.java:811)
	at org.sqlite.core.CoreStatement.exec(CoreStatement.java:75)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:83)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeQuery(FilterChainImpl.java:2427)

**Comment by feimengwang** [comment]
Now it works for me
