### ISSUE TITLE
Racy Initialization in SQLiteJDBCLoader

### ISSUE THREAD

**Issue by trohwer** [xerial/sqlite-jdbc#269]
If one creates a number of connections concurrently initially, one gets errors like

Exception in thread "Thread-15" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:71)
        at org.sqlite.core.DB.open(DB.java:174)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at Test3.run(Test3.java:26)
        at java.lang.Thread.run(Thread.java:748)

The (- or at least - one) problem is, that the method

initialize() in SQLiteJDBCLoader

can be entered concurrently (only loadNativeLibrary is covered  by synchonized)
and then one running instance can delete the extracted files of the other running instance.
The mechanism with the lck files is not reliable; the lock file is created after the dll file.

Here is a test program:

`import java.sql.*;

public class Test3 implements Runnable {
  static int N= 20;
  static java.util.concurrent.CyclicBarrier cb=
    new java.util.concurrent.CyclicBarrier(N);
  public static void main(String[] args) throws Exception {
    Class.forName("org.sqlite.JDBC");
    for (int i=0; i<N; i++) {
      (new Thread(new Test3(i))).start();
    }
  }

  int d;
  public Test3(int d) {
    this.d= d;
  }

  public void run() {
    String url= "jdbc:sqlite::memory:";
    try{
      cb.await();
      Thread.sleep(0,100*d);
      DriverManager.getConnection(url).close();
    } catch(Exception e) {
      throw(new RuntimeException(e));
    }
  }
}
`
You may have to fiddle a bit with the delay to reproduce the bug. Even if it does not trigger,
observe the multiple dll files created. But this does not only occur in this artifical situation. On a jetty web container it happens almost all the time for me.

The whole initialization is somewhat convoluted (Driver/NativeDB/SQLiteJDBCLoader). Probably one should restructure this, but a quick improvement is moving the synchronized to the initialize method
to prevent that race. I will send a pull request.

**Comment by trohwer** [comment]
When implementing this, I realized, that there was some change to create the lock file earlier
two months ago; I was working on an older version. But I think, it is still possible, that multiple dll files are extracted, which is a bit ugly. But please disregard this until a have another careful look.

**Comment by trohwer** [comment]
I can reproduce this on trunk, changing to N=40, 50*d.

The actual commit "Fix issue #197: create lock-file before lib"
also does not do, what it claims. The lock file is
still created after the lib file, it was just moved before writing the content
of the lib file:

FileOutputStream writer = new FileOutputStream(extractedLibFile);
            if(!extractedLckFile.exists()) {
                new FileOutputStream(extractedLckFile).close();
            }

Even if we really move the creation of the lock file before the creation of the lib file,
I would avoid assuming, that these file operations are seen in the same order
on some other thread. And there are multiple lib/lock files created even during races,
that don't exhibit the Exception. So I still propose, to move the synchronized.
