### ISSUE TITLE
Linux x86 Native Library

### ISSUE THREAD

**Issue by danap** [xerial/sqlite-jdbc#34]
The current native library for Linux x86 is giving the following exception:

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:161)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:224)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:78)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:187)
	at com.dandymadeproductions.myjsqlview.gui.LoginFrame.accessCheck(LoginFrame.java:1191)

By reverting by to and earlier library, libsqlitejdbc.so size 858.1kb, from the 3.8.8.2 build
I believe fixes the error.

Dana M. Proctor
MyJSQLView Project Manager

**Comment by xerial** [comment]
Thanks for reporting. 

Could you show me the result of `ldd --version` in your platform?
```
$ ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.12) 2.15
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by xerial** [comment]
And also try sqlite-jdbc-3.8.10.1

**Comment by danap** [comment]
Hello,

The current development system I'm using shows:

danap@jtiger:~$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

While an update Linux system that I have not tested on shows:

-bash-4.3$ ldd --version
ldd (GNU libc) 2.20

I have updated the libraries to 3.8.10.1 and now the issue with the Linux/x86 library is
resolved.

Thank you,

Dana M. Proctor
MyJSQLView Project Manager.

**Comment by danap** [comment]
On Mon, May 11, 2015 11:03 am, Taro L. Saito wrote:
> And also try sqlite-jdbc-3.8.10.1
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/xerial/sqlite-jdbc/issues/34#issuecomment-100937161

Hello Saito,

I have left comments to the issue #34 and closed on github, this morning.

Thank you for the resolution.

danap.

**Comment by xerial** [comment]
Thanks for checking. I'm glad to hear that.
