### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8

### ISSUE THREAD

**Issue by zbeedatm** [xerial/sqlite-jdbc#351]
I keep getting this error:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)

Using sqlite-jdbc-3.15.1, tried upgrading/downgrading to other versions (till 3.7) but didn't help.

`private void openConnection(String userName, String projectName, String configName)
			throws SQLException, ClassNotFoundException {
		final String fileName = getDbName(userName, projectName, configName);
		Class.forName("org.sqlite.JDBC");
		final String url = "jdbc:sqlite:" + fileName;
		connection = DriverManager.getConnection(url);
		connection.setAutoCommit(true);
	}`

It might be that I need to use synchronized on methods using the connection. Will give it a try.

**Comment by tildedave** [comment]
We had this issue and the patch in https://github.com/xerial/sqlite-jdbc/issues/269 happened to fix it.

I believe the fix first landed in 3.20.1.

**Comment by zbeedatm** [comment]
I recall that I upgraded to 3.23 and it didn't work for me.
However, I took 3.20.1 and ran in parallel (multi threading - 10 threads) in a loop:
100-300 iterations - Worked
400 iterations - Failed with same error

Seems that you still have an issue there.

**Comment by zbeedatm** [comment]
Seems to be my bad.... I replaced the jar in the client that is running the junits and not the one on the server.
I replaced the jar in server side and so far, so good.
