### ISSUE TITLE
Support long pathnames (more than 255 characters) on Windows

### ISSUE THREAD

**Issue by buko** [xerial/sqlite-jdbc#354]
Attempt to open a database with a pathname of more than 255 characters results in the following error:

```
Caused by: java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:410)
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:398)
```

The underlying issue is that Windows 10, until very recently, doesn't support pathnames longer than 255 characters unless you do some hackery.

This isn't *really* an issue in xerial or sqlite but I wonder if the code could be modified to present a more informative error. Xerial does not relay the underlying sqlite error code (ERROR 14 CANT_OPEN) and the message "The database has been closed" is pretty misleading. It took me a while to track down this problem and it might save others some time if we could get a more specific error message indicating the database file pathname is too long.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
> Doesn't seem to work though it should according to the docs.

It is not implemented, this would need to define a new pragma and use it when opening the database.

**Comment by gotson** [comment]
I was reading https://www.sqlite.org/vfs.html and it seems using `vfs=win32-longpath` should work.

**Comment by gotson** [comment]
I actually checked the code, and if you set `?vfs=win32-longpath` it will be passed to the `sqlite3_open_v2()` call, so it should work fine.

**Comment by gotson** [comment]
You need to use the `file:` URI: https://www.sqlite.org/uri.html for it to work:

```
ds.setUrl("jdbc:sqlite:file:yourfile.db?vfs=win32-longpath");
```
