### ISSUE TITLE
Provide more information when a Foreign Key Constraint is violated

### ISSUE THREAD

**Issue by buko** [xerial/sqlite-jdbc#367]
When a FK Constraint is violated the driver produces the following error:

````
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_FOREIGNKEY]  A foreign key constraint failed (FOREIGN KEY constraint failed)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:825)
	at org.sqlite.core.DB.executeUpdate(DB.java:863)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
````

In a large database (70+ tables) it can be very, very difficult to track down which FK constraint is being violated. The driver should produce more information about the constraint that was violated. Minimally it should include the table name but ideally it should also provide some sort of (not necessarily unique) identifier for the specific constraint.

**Comment by buko** [comment]
Well that's not good. I'll go ahead and close this issue. It might be worthwhile following up with SQLite but I understand they're very unlikely to make any modification on this front.
