### ISSUE TITLE
sqlite dbcp

### ISSUE THREAD

**Issue by xuyang198711** [xerial/sqlite-jdbc#37]
hello~：
I'm using dbcp by  sqlite。

code：
BasicDataSource tempDbs = new BasicDataSource();
                    tempDbs.setDriverClassName("org.sqlite.JDBC");
                    tempDbs.setUrl("jdbc:sqlite:db/temp.db");
                    //tempDbs.setUsername("root");
                    //tempDbs.setPassword("root");
                    tempDbs.setInitialSize(20);
                    tempDbs.setMaxTotal(20);
                    tempDbs.setMaxIdle(50);
                    tempDbs.setMinIdle(5);
                    tempDbs.setMaxWaitMillis(1000);

                tempDbs.getConnection();
it catch a exception:
          Exception in thread "main" java.sql.SQLException: Cannot create PoolableConnectionFactory (isValid() returned false)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2291)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2038)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at com.dtdream.vehicle.util.ConnectionUtil.getTempConnection(ConnectionUtil.java:97)
	at com.dtdream.vehicle.util.ConnectionUtil.main(ConnectionUtil.java:68)
Caused by: java.sql.SQLException: isValid() returned false
	at org.apache.commons.dbcp2.PoolableConnection.validate(PoolableConnection.java:284)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:357)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2287)
	... 4 more

jars :           sqlite-jdbc-3.8.7.jar   commons-dbcp2-2.1.jar   commons-pool2-2.3.jar

pelase help!
thanks!

**Comment by gitblit** [comment]
Try updating to 3.8.10.1.  I think you'll have better luck.
