### ISSUE TITLE
Can't use driver when compiling graalvm binary

### ISSUE THREAD

**Issue by mageddo** [xerial/sqlite-jdbc#413]
I've created a small application using sqlite-jdbc driver and it works as well, but after compile the jar using graalvm native-image command the application don't working, I get the following error when I try to run some sql query

```
Failed to load native library:sqlite-unknown-f42d3920-dfd1-4cad-ba79-7e95f6d231fa-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: Unsupported JNI version 0xffffffff, required by /var/tmp/sqlite-unknown-f42d3920-dfd1-4cad-ba79-7e95f6d231fa-libsqlitejdbc.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V [symbol: Java_org_sqlite_core_NativeDB__1open_1utf8 or Java_org_sqlite_core_NativeDB__1open_1utf8___3BI]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
	at org.sqlite.core.NativeDB._open_utf8(NativeDB.java)
	at org.sqlite.core.NativeDB._open(NativeDB.java:78)
	at org.sqlite.core.DB.open(DB.java:195)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at com.mageddo.utils.MigrationUtils.migrate(MigrationUtils.java:15)
	at com.mageddo.Application.main(Application.java:15)
```

[Here an example project](https://github.com/mageddo/graalvm-examples/tree/1137b7bf48/sqlite) of how to reproduce the issue

**Comment by mageddo** [comment]
I'm using version: `org.xerial:sqlite-jdbc:3.27.2`

**Comment by xerial** [comment]
Thanks for the report. So it seems GraalVM cannot load native library for JNI.

I need to understand how GraalVM can support JNI.

**Comment by xerial** [comment]
https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#java-native-interface-jni

It seems Graal's JNI support is a bit limited.

**Comment by mageddo** [comment]
Yep, I don't know how difficult it could be to make this adaptation

**Comment by xerial** [comment]
It seems we need to register entries for Refleciton:
https://github.com/oracle/graal/blob/master/substratevm/JNI.md#reflection

**Comment by mageddo** [comment]
I've created [JNIReflectionClasses.java](https://github.com/mageddo/graalvm-examples/blob/c482b2e/sqlite/src/main/java/com/mageddo/sqlite/JNIReflectionClasses.java) for that purpose, still not working.

----------

I've read that graal make some translation on the `native` methods at compile time, maybe the issue could be there [[1]](https://github.com/oracle/graal/blob/master/substratevm/JNI.md#java-to-native-method-calls)

**Comment by borkdude** [comment]
I'm also interested in this.

**Comment by edigonzales** [comment]
Any news on this issue?

**Comment by mageddo** [comment]
The graalvm example using sqlite is now working, [here the working version](https://github.com/mageddo/graalvm-examples/tree/59f1f1bf09894681edfddaa100b4504770ad0685), special thanks to @mukel 

here the fix pull request https://github.com/mageddo/graalvm-examples/pull/2

**Comment by ericdallo** [comment]
Hey @mageddo @xerial  I could make my Clojure app using sqlite compile with Graalvm for Windows/Linux/MacOS successfully [here](https://github.com/ericdallo/sqlite-graalvm-sample/releases), but when compiling a Linux static binary, it doesn't work, it seems that the shipped sqlite lib is not static, but dynamic.
Running the static binary I get:
```java
Failed to load native library:sqlite-unknown-5db626ec-518e-4fc0-a5f6-a21818a0c5c8-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-unknown-5db626ec-518e-4fc0-a5f6-a21818a0c5c8-libsqlitejdbc.so
Exception in thread "main" java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql.DriverManager.getConnection(DriverManager.java:189)
        at next.jdbc.connection$get_driver_connection.invokeStatic(connection.clj:141)
        at next.jdbc.connection$url_PLUS_etc$reify__747.getConnection(connection.clj:357)
        at next.jdbc.connection$make_connection.invokeStatic(connection.clj:385)
        at next.jdbc.connection$fn__760.invokeStatic(connection.clj:406)
        at next.jdbc.connection$fn__760.invoke(connection.clj:406)
        at next.jdbc.protocols$fn__563$G__558__570.invoke(protocols.clj:24)
        at next.jdbc.connection$fn__764.invokeStatic(connection.clj:415)
        at next.jdbc.connection$fn__764.invoke(connection.clj:406)
        at next.jdbc.protocols$fn__563$G__558__570.invoke(protocols.clj:24)
        at next.jdbc$get_connection.invokeStatic(jdbc.clj:155)
        at sqlite_graalvm_sample.core$insert.invokeStatic(core.clj:15)
        at sqlite_graalvm_sample.core$_main.invokeStatic(core.clj:36)
        at sqlite_graalvm_sample.core$_main.doInvoke(core.clj:36)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at sqlite_graalvm_sample.core.main(Unknown Source)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
        ... 24 more
```

**Comment by mageddo** [comment]
@ericdallo When you compile the binary using Graal you need to specify which files will be bundled within the binary file, something [like this][1] , take a look.

[1]: https://github.com/mageddo/graalvm-examples/blob/59f1f1bf09894681edfddaa100b4504770ad0685/sqlite/build.gradle#L28
