### ISSUE TITLE
"Error opening connection" with sqlite-jdbc-3.8.7.jar  (arm cortex a9 soft float)

### ISSUE THREAD

**Issue by antonio-dibacco** [xerial/sqlite-jdbc#44]
I used sqlite-jdbc-3.8.7.jar to compile a jar that tries to open a connection to a database. 
This is the error I get on a ARM CORTEX A9 (soft float). I also tried to use the sqlite-jdbc-3.8.11.jar but I get an UnsatisfiedLinkError exception and I will open another issue for this problem.

The same jars are working fine on Ubuntu on x86. I think that working on ARM is quite important for a this library.

zynq> java -jar sqlite-3.8.7.jar 
java.sql.SQLException: Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:140)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.argonnetech.sqlite.SQLite.main(SQLite.java:14)
Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=arm
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:284)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
	at org.sqlite.core.NativeDB.load(NativeDB.java:53)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:136)
	... 9 more

**Comment by xerial** [comment]
Will be addressed in #45
