### ISSUE TITLE
use custom sqlite dynamic library instead of built-in throws java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8

### ISSUE THREAD

**Issue by yidu0331** [xerial/sqlite-jdbc#440]
because built-in sqlite.so don't include dbstat, and we need it. so we download src and compile it. and then use jar xvf/cvf replace built-in sqlite.so. when we run java app. it throws "java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8".
how to repeat:
1、download sqlite-amalgamation-3290000.zip from sqlite.org
2、compile it as follows:
gcc -lpthread -DSQLITE_ENABLE_FTS4  -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_EXPLAIN_COMMENTS shell.c sqlite3.c -ldl -lm -shared -fPIC -o libsqlitejdbc.so
3、replace built-in so.
jar -xzf sqlite-jdbc-3.28.0.jar
cp libsqlitejdbc.so to org/sqlite/native/Linux/x86_64, and replace built-in.
jar -cfM sqlite-jdbc-3.28.0.jar ./
4、run app，as follows:
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:78)
	at org.sqlite.core.DB.open(DB.java:195)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)

**Comment by yidu0331** [comment]
by the way, the sqlite-jdbc version is prior then so. i test the 3.28,3.21, all of them are throw exception. is the problem caused of this?

**Comment by yidu0331** [comment]
by the way, the sqlite-jdbc version is prior then so. i test the 3.28,3.21, all of them are throw exception. when we compile executable. it can run without error

**Comment by yidu0331** [comment]
resolved
