### ISSUE TITLE
java.lang.Exception: No native library is found for os.name=SunOS and os.arch=sparcv9

### ISSUE THREAD

**Issue by viru-j** [xerial/sqlite-jdbc#469]
When i am running app.. getting below exception
`java.sql.SQLException: Error opening connection
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:140)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at EngineManager.createDb(EngineManager.java:102)
        at EngineManager.initializeEngine(EngineManager.java:79)
        at EngineManager.main(EngineManager.java:43)
Caused by: java.lang.Exception: No native library is found for os.name=SunOS and os.arch=sparcv9
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:284)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
        at org.sqlite.core.NativeDB.load(NativeDB.java:53)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:136)`

**Comment by michael-o** [comment]
You obviously have to compile on your own for Solaris SPARC.

**Comment by viru-j** [comment]
do you have steps to build it...?

**Comment by michael-o** [comment]
Look at the `Makefile` and add Solaris/SPARC to it.

**Comment by despair86** [comment]
yes the `gmake native` target works fine here. You may need to `touch` database files on creation, i'll describe in a separate issue

**Comment by despair86** [comment]
this might help if you somehow still use sun studio
```diff
diff --git a/Makefile.common b/Makefile.common
index 9145cb0..d7d84f1 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -57,9 +57,9 @@ endif
 # cross-compilation toolchain prefix (e.g. "arm-linux-gnueabi-")
 CROSS_PREFIX :=

-Default_CC        := $(CROSS_PREFIX)gcc
+Default_CC        := $(CROSS_PREFIX)cc
 Default_STRIP     := $(CROSS_PREFIX)strip
-Default_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -Os -fPIC -fvisibility=hidden
+Default_CCFLAGS   := -m64 -I$(JAVA_HOME)/include -Ilib/inc_linux -O4 -xspace -fPIC -fvisibility=hidden
 Default_LINKFLAGS := -shared
 Default_LIBNAME   := libsqlitejdbc.so
 Default_SQLITE_FLAGS  :=
```

**Comment by gotson** [comment]
Closing this, as there is no way we can compile that using dockcross.
