### ISSUE TITLE
Updating from 3.23.1 to 3.30.1 breaks

### ISSUE THREAD

**Issue by SElab2019** [xerial/sqlite-jdbc#477]
When I try to upgrade sqlite-jdbc from 3.23.1 to the version after 3.25.2. The following code breaks.
```
public class Demo {

    private final static String FILE_NAME = "test.db";

    @Test
    public void givenExistingItem_whenAddItemWithSameUrl_thenNothingHappens() {
    	SqLiteDbRepository repository = new SqLiteDbRepository();
    	repository.init(FILE_NAME);
        LocalDateTime time = LocalDateTime.now();
        LocalDateTime timeAfter1Hour = time.plusHours(1);
        ForumThread ft = generateUniqueForumThread(time);
        ForumThread ftAfter1Hour = generateUniqueForumThread(timeAfter1Hour);
        ftAfter1Hour.setUniqueUrl(ft.getUniqueUrl()); // Make the URL the same
        repository.addOnlyIfUrlUnique(ft);
        repository.addOnlyIfUrlUnique(ftAfter1Hour);
        
    }
    private ForumThread generateUniqueForumThread(LocalDateTime time) {
        ForumThread ft = new ForumThread();
        ft.setDateTime(time);
        ft.setBody(UUID.randomUUID().toString());
        ft.setTitle(UUID.randomUUID().toString());
        ft.setUniqueUrl(UUID.randomUUID().toString());
        return ft;
    }
}
```
```
public class SqLiteDbRepository {
	
    private Connection c = null;
    private final static String TABLE = "FORUMTHREADS";
    
    private void createTableIfMissing() {
        try (Statement statement = c.createStatement()) {
            String sql = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
                    "URL TEXT PRIMARY KEY NOT NULL UNIQUE, " +
                    "TITLE TEXT NOT NULL, " +
                    "BODY TEXT NOT NULL, " +
                    "DATETIME TEXT NOT NULL, " +
                    "ISSENT INTEGER" +
                    ")";
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }
    
    private void executeUpdate(String sql, String... args) throws SQLException {
    	
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            int index = 1;
            for (String arg : args) {
            	System.out.println("!!!" + arg + "!!!" + index);
                ps.setString(index++, arg);
            }
            ps.executeUpdate();
        }
    }
    
    public void init(String fileName) {
        try {
            Class.forName("org.sqlite.JDBC");
            String dbFolderPath = "null";
            c = DriverManager.getConnection("jdbc:sqlite:" + dbFolderPath + fileName);
            createTableIfMissing();
        } catch (ClassNotFoundException|SQLException e) {
            e.printStackTrace();
            throw new RuntimeException(e); // FIXME: A better thing to do?
        }
    }


    public void addOnlyIfUrlUnique(ForumThread forumThread) {
    	
        try {
            executeUpdate("INSERT INTO " + TABLE + " ('URL', 'TITLE', 'BODY', 'DATETIME', 'ISSENT') VALUES (?, ?, ?, ?, ?)",
                    forumThread.getUniqueUrl(), forumThread.getTitle(), forumThread.getBody(),
                    forumThread.getDateTime().toString(), forumThread.isSent() ? "1" : "0");
        } catch (SQLException e) {
            if (e.toString().contains("SQLITE_CONSTRAINT_PRIMARYKEY")) {
                return; // This is expected. Do nothing.
            }
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

}
```
```
public class ForumThread {

    private String uniqueUrl;
    private String title;
    private String body;
    private LocalDateTime dateTime;
    private boolean isSent;

    public ForumThread(ForumThread forumThread) {
        title = forumThread.getTitle();
        uniqueUrl = forumThread.getUniqueUrl();
        body = forumThread.getBody();
        dateTime = forumThread.getDateTime();
        isSent = forumThread.isSent();
    }

    public ForumThread() {
        title = "";
        uniqueUrl = "";
        body = "";
        dateTime = LocalDateTime.now();
        isSent = false;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUniqueUrl() {
        return uniqueUrl;
    }

    public void setUniqueUrl(String uniqueUrl) {
        this.uniqueUrl = uniqueUrl;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public void setDateTime(LocalDateTime date) {
        this.dateTime = date;
    }

    public boolean isSent() {
        return isSent;
    }

    public void setSent(boolean sent) {
        isSent = sent;
    }
}
```
The test should pass, but it throws an error:
```
java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: FORUMTHREADS.URL)
	at Se.lab.Sqlite_jdbc_Demo.SqLiteDbRepository.addOnlyIfUrlUnique(SqLiteDbRepository.java:69)
	at Se.lab.Sqlite_jdbc_Demo.Demo.givenExistingItem_whenAddItemWithSameUrl_thenNothingHappens(Demo.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: FORUMTHREADS.URL)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.execute(DB.java:854)
	at org.sqlite.core.DB.executeUpdate(DB.java:895)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
	at Se.lab.Sqlite_jdbc_Demo.SqLiteDbRepository.executeUpdate(SqLiteDbRepository.java:41)
	at Se.lab.Sqlite_jdbc_Demo.SqLiteDbRepository.addOnlyIfUrlUnique(SqLiteDbRepository.java:61)
	... 24 more


```

**Comment by gotson** [comment]
is this still an issue ?

**Comment by gotson** [comment]
Closing this as no feedback was received.
