### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V with Docker

### ISSUE THREAD

**Issue by chocolate213** [xerial/sqlite-jdbc#486]
I got this error with sqlite-jdbc on docker:
```text
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.core.NativeDB._open(NativeDB.java:78) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.core.DB.open(DB.java:195) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[sqlite-jdbc-3.28.0.jar:na]
        at org.sqlite.JDBC.connect(JDBC.java:90) ~[sqlite-jdbc-3.28.0.jar:na]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_181]
        at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[na:1.8.0_181]
```
I've tried several versions of sqlite-jdbc(include 3.21.0.1, 3.23.1, 3.25.2, 3.18.0, 3.8.11.2, 3.7.2, 3.28.0), but all of them didn't work. and I also checked the temp dir permission, there is no `noexec` on it.

Here is my environmential information: 

Docker image OS info:
```shell
$ cat /cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core) 
$ uname -a
Linux commonconfig-6d7f67f5db-rrl5k 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Java version: 

```text
# java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by johannespostler** [comment]
Are you sure that your database file is writeable to?

**Comment by chocolate213** [comment]
> Are you sure that your database file is writeable to?

No, I run it in `In-Memory` mode. It can be run on my local machine(Windows10 Pro), Linux(version same as Docker image), just not worked with Docker.

**Comment by tbmale** [comment]
I have the same error trying to use Metabase v0.36.6!
My env:
```
[ ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[ ~]$ java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode
```

Also tried with :
```
[ ~]$ ~/metabase/jdk8u265-b01-jre/bin/java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```

On Windows10 with the same AdoptOpenJDK version it works.

**Comment by gotson** [comment]
Is this still an issue?

**Comment by gotson** [comment]
Closing this as no feedback was received.
