### ISSUE TITLE
Unable to open the database file when query takes a while

### ISSUE THREAD

**Issue by Toni-STF** [xerial/sqlite-jdbc#514]
In Java when I try to run a slow query I get the following error:
```
org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
       at org.sqlite.core.DB.newSQLException(DB.java:1010)
       at org.sqlite.core.DB.newSQLException(DB.java:1022)
       at org.sqlite.core.DB.execute(DB.java:864)
       at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
       at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:75)
       at data.QueryExecutor.executeSQLLiteSelect(QueryExecutor.java:734)
       at data.sqlite.SQLite_Selects.selectSharedSites(SQLite_Selects.java:551)
       at gui.panels.SharedSitePanel.getTableModel(SharedSitePanel.java:151)
       at gui.panels.SharedSitePanel.getNoInqueryTable(SharedSitePanel.java:179)
       at gui.panels.SharedSitePanel.getTabbedPane(SharedSitePanel.java:93)
       at gui.panels.SharedSitePanel.getContentPanel(SharedSitePanel.java:84)
       at gui.panels.SharedSitePanel.<init>(SharedSitePanel.java:71)
       at gui.objects.menu.ViewMenu.actionPerformed(ViewMenu.java:133)
       at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
       at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
       at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
       at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
       at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
       at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
       at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
       at java.awt.Component.processMouseEvent(Component.java:6533)
       at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
       at java.awt.Component.processEvent(Component.java:6298)
       at java.awt.Container.processEvent(Container.java:2236)
       at java.awt.Component.dispatchEventImpl(Component.java:4889)
       at java.awt.Container.dispatchEventImpl(Container.java:2294)
       at java.awt.Component.dispatchEvent(Component.java:4711)
       at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
       at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
       at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
       at java.awt.Container.dispatchEventImpl(Container.java:2280)
       at java.awt.Window.dispatchEventImpl(Window.java:2746)
       at java.awt.Component.dispatchEvent(Component.java:4711)
       at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
       at java.awt.EventQueue.access$500(EventQueue.java:97)
       at java.awt.EventQueue$3.run(EventQueue.java:709)
       at java.awt.EventQueue$3.run(EventQueue.java:703)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
       at java.awt.EventQueue$4.run(EventQueue.java:731)
       at java.awt.EventQueue$4.run(EventQueue.java:729)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
       at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
       at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
       at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
       at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
       at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
I already tried to set the busytimeout to 0. When I run fast queries no error appears.
Do somebody know how to fix this?!

**Comment by Toni-STF** [comment]
This question is still open.

If a query takes to long, the query will be interupted by this Exception very early(after 5-15 Seconds)

**Comment by gotson** [comment]
How do you get the connection? Is the in-flight query read or write? Do you use a connection pool?

**Comment by gotson** [comment]
> I already tried to set the busytimeout to 0

This will not work, it basically tells SQLite to fail immediately if there's a lock.

https://www.sqlite.org/c3ref/busy_timeout.html :
> Calling this routine with an argument less than or equal to zero turns off all busy handlers.

**Comment by gotson** [comment]
Closing this as no feedback was received.
