### ISSUE TITLE
DatabaseMetaData.getColumns fails with NPE

### ISSUE THREAD

**Issue by andyjefferson** [xerial/sqlite-jdbc#52]
If I create a table in SQLite (jdbc:sqlite:test1.db), say something like this
CREATE TABLE DOCUMENT
(
    ID INTEGER PRIMARY KEY autoincrement,
    "NAME" varchar(255) NULL
)

then I exit my app (and SQLite). I then restart the app and call
DatabaseMetaData.getColumns(null, null, null, null);

this gives
java.lang.NullPointerException
        at org.sqlite.core.CoreDatabaseMetaData.escape(CoreDatabaseMetaData.java:182)
        at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getColumns(JDBC3DatabaseMetaData.java:1115)

I would expect it to return the columns for all tables present in this SQLite database.

Looking at the source code, 
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java#L1115
it tries to escape a null as if there is a single table being returned from this method always? (or am I reading it wrong?)

This method has to be capable of returning many tables, and taking a "tableNamePattern" of null to mean don't restrict the tables (to be consistent with the JDBC spec, and all other JDBC drivers for other RDBMS). If I knew what the low level SQLite SQL would be to get such schema info I could try it in my own clone of SQLite-jdbc source. Any ideas/help?

**Comment by andyjefferson** [comment]
In fact SQLDroid seems to do a much more reasonable thing (IMHO), see
https://github.com/SQLDroid/SQLDroid/blob/master/src/main/java/org/sqldroid/SQLDroidDatabaseMetaData.java#L133
where it uses getTables(...) to get the tables implied by the input tableNamePattern and then gets the column info for each of those tables using "PRAGMA table_info(tableName)".

**Comment by andyjefferson** [comment]
This is now fixed in v3.8.11.2. Works for me. Thx
