### ISSUE TITLE
Cannot create backup

### ISSUE THREAD

**Issue by betonetotbo** [xerial/sqlite-jdbc#520]
My URL connection is: `jdbc:sqlite:database.db`
My tried backup commands: 
  - `backup to \"d:/temp/backup-sqlite.db\"`
  - `backup database.db to \"d:/temp/backup-sqlite.db\"`
  - `backup \"database.db\" to \"d:/temp/backup-sqlite.db\"`
  - `backup database to \"d:/temp/backup-sqlite.db\"`

All of them returns error:

```java
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "backup": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:1010) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.core.DB.newSQLException(DB.java:1022) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.core.DB.throwex(DB.java:987) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.core.DB.prepare(DB.java:264) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[sqlite-jdbc-3.32.3.1.jar:na]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[HikariCP-3.4.5.jar:na]
```

**Comment by betonetotbo** [comment]
I was using the `Connection.prepareStatement`. 

Now, I have tried `Connection.createStatement().execute("backup to \"path/to/file\"")` and it worked!

Why?

**Comment by dkfellows** [comment]
It's a special command implemented by the Java part of the driver, not the underlying database engine (it's an API call on that level). It must be called _exactly_ as documented.

No idea why it wasn't just done as a direct call on an `SQLiteConnection`, but it isn't.
