### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by sujkwatcher** [xerial/sqlite-jdbc#522]
使用了sqlite-jdb执行sqlite操作。异常。
源码
```
public static void main(String[] args) {
	SpringApplication.run(DemoApplication.class, args);
	Connection c = null;
	try {
		Class.forName("org.sqlite.JDBC");
		c = DriverManager.getConnection("jdbc:sqlite:/mnt/user/r6/sujk/test.db");

		Statement stmt = c.createStatement();
		String sql = "CREATE TABLE COMPANY " +
				"(ID INT PRIMARY KEY     NOT NULL," +
				" NAME           TEXT    NOT NULL, " +
				" AGE            INT     NOT NULL, " +
				" ADDRESS        CHAR(50), " +
				" SALARY         REAL)";
		stmt.executeUpdate(sql);
		stmt.close();
		c.close();
	} catch (Exception e) {
		System.err.println(e.getClass().getName() + ": " + e.getMessage());
		System.exit(0);
	}
	System.out.println("Opened database successfully");
}
```
maven依赖
```
 <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.8.11.1</version>
 </dependency>
```
异常
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:161)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.example.demo.DemoApplication.main(DemoApplication.java:18)
```
系统版本
```
Linux (none) 4.9.37 #13 SMP Wed Jul 8 16:47:49 CST 2020 armv7l GNU/Linux
```

**Comment by sujkwatcher** [comment]
Thanks
