### ISSUE TITLE
Unsatisfied link CentOS linux

### ISSUE THREAD

**Issue by ampublic** [xerial/sqlite-jdbc#56]
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V 
        at org.sqlite.core.NativeDB._open(Native Method) ~[xxx.jar:na] 
        at org.sqlite.core.DB.open(DB.java:161) ~[xxx.jar:na] 
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:145) ~[xxx.jar:na] 
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66) ~[xxx.jar:na] 
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21) ~[xxx.jar:na] 
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23) ~[xxx.jar:na] 
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[xxx.jar:na] 
        at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[xxx.jar:na] 
        at org.sqlite.JDBC.connect(JDBC.java:88) ~[xxx.jar:na] 
        at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[na:1.7.0_85] 
        at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[na:1.7.0_85] 

gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 

ldd --version
ldd (GNU libc) 2.12

java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

uname -r
2.6.32-573.3.1.el6.x86_64

sqlite3 -version
3.6.20
Installed Packages
Name        : sqlite
Arch        : x86_64
Version     : 3.6.20
Release     : 1.el6_7.2

**Comment by yonisolo** [comment]
I got the same in ARM raspbian #57

**Comment by ampublic** [comment]
Can you post the above information? I see you are running gcc 4.6.3, but what Java are you using?

**Comment by yonisolo** [comment]
oracle java 1.8.0_60-b27

**Comment by xerial** [comment]
Actually I have tested the latest version on CentOS 5. I think this has already resolved.
