### ISSUE TITLE
No native library found for darwin aarch64

### ISSUE THREAD

**Issue by felipecsl** [xerial/sqlite-jdbc#562]
Failed on new Apple silicon laptops (M1/arm64)
```
Caused by: java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:410) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:398) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.jobrunr.storage.sql.common.SqlStorageProviderFactory.getStorageProviderUsingDataSource(SqlStorageProviderFactory.java:25) ~[jobrunr-1.2.0.jar:na]
	... 45 common frames omitted
Caused by: java.lang.Exception: No native library found for os.name=Mac, os.arch=aarch64, paths=[/Users/felipelima/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[sqlite-jdbc-3.32.3.2.jar:na]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[sqlite-jdbc-3.32.3.2.jar:na]
	... 52 common frames omitted
```

**Comment by felipecsl** [comment]
Just saw #558 
would yall be able to cut a new release with that change, please?
Thanks!

**Comment by felipecsl** [comment]
As a workaround, downloading [`libsqlitejdbc.jnilib`](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/resources/org/sqlite/native/Mac/aarch64/libsqlitejdbc.jnilib) and placing it in `~/Library/Java/Extensions` fixes it

**Comment by xerial** [comment]
Just released 3.32.3.3 with M1 support :)

**Comment by felipecsl** [comment]
Worked :) thanks!

**Comment by suopovate** [comment]
> As a workaround, downloading [`libsqlitejdbc.jnilib`](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/resources/org/sqlite/native/Mac/aarch64/libsqlitejdbc.jnilib) and placing it in `~/Library/Java/Extensions` fixes it

it can resolve the problem that I can't open my plugin in idea(using sqllite)?
I put this file to the target directory, but I don't know how it works,and I still can't using the plugin in my idea.

**Comment by jzherran** [comment]
Hey folks, I have the same issue I can't use the latest version of the xerial/sqlite0jdbc because broke some communication related to the kernel that I used to connect.

But when I add the library in the folder as referred @felipecsl I received the following error:

```bash
Syntax error (ClassNotFoundException) compiling at (/private/var/folders/kz/rjmcjggd5tscjxcjktp6z4sc0000gn/T/form-init9543403292769450227.clj:1:125).
org.sqlite.Collation
```

Do you know maybe what is the error?
