### ISSUE TITLE
Jar does not work with Raspberry Pi

### ISSUE THREAD

**Issue by orang3-juic3** [xerial/sqlite-jdbc#567]
```
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.8.7-9cb91915-7f2c-4e76-af82-5bc7c30d9d63-libsqlitejdbc.so: /tmp/sqlite-3.8.7-9cb91915-7f2c-4e76-af82-5bc7c30d9d63-libsqlitejdbc.so: cannot open shared object file: No such file or directory
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open(java.lang.String, int)'
    at org.sqlite.core.NativeDB._open(Native Method)
    at org.sqlite.core.DB.open(DB.java:161)
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
    at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
    at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
    at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
    at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
    at org.sqlite.JDBC.createConnection(JDBC.java:114)
    at org.sqlite.JDBC.connect(JDBC.java:88)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
    at me.alex.Main.firstTimeDatabaseSetup(Main.java:62)
    at me.alex.Main.main(Main.java:26)
```
This is the build i'm using 
[sqlite-jdbc-3.8.7.zip](https://github.com/xerial/sqlite-jdbc/files/5718465/sqlite-jdbc-3.8.7.zip)
I made the library with
```
make linux-arm
```

**Comment by orang3-juic3** [comment]
fixed by using an older version of this library..
