### ISSUE TITLE
sqlite-jdbc-3.32.3.2.jar can't support mips system

### ISSUE THREAD

**Issue by Jeremy-zgp** [xerial/sqlite-jdbc#624]
```
java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
	at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
	at org.sqlite.JDBC.connect(JDBC.java:90) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:251) ~[java.sql:?]

Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=mips64el, paths=[/usr/lib:/usr/java/packages/lib:/usr/lib/mips64el-linux-gnuabi64/jni:/lib/mips64el-linux-gnuabi64:/usr/lib/mips64el-linux-gnuabi64:/usr/lib/jni:/lib:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367) ~[sqlite-jdbc-3.32.3.2.jar!/:?]
```

**Comment by gotson** [comment]
You could try to add support via https://github.com/dockcross/dockcross#dockcrosslinux-mipsel

**Comment by xiaoliying0912** [comment]
I have the same problem. I have update problem use  sqlite-jdbc-3.36.0.1 .   but the problem haven't solve.    what shoud i do ? who tell me .

**Comment by Paradox98** [comment]
It's not an architecture, I need the support of both mips64 and mips64el architectures.
