### ISSUE TITLE
make test failed in sqlite-jdbc@3.36.0.1

### ISSUE THREAD

**Issue by Tom-python0121** [xerial/sqlite-jdbc#625]
I meet a problem:make test failed in sqlite-jdbc@3.36.0.1 on openEuler20
### Steps to reproduce the issue

```console
[root@localhost spack-src]#make test
mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.xerial:sqlite-jdbc >-----------------------
[INFO] Building SQLite JDBC 3.36.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ sqlite-jdbc ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sqlite-jdbc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 14 resources
[INFO] Copying 1 resource to META-INF/services
[INFO] Copying 1 resource
[INFO] Copying 3 resources to META-INF/maven/org.xerial/sqlite-jdbc
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ sqlite-jdbc ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 49 source files to /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/target/classes
[WARNING] /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/src/main/java/org/sqlite/core/DB.java: Some input files use or override a deprecated API.
[WARNING] /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/src/main/java/org/sqlite/core/DB.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/src/main/java/org/sqlite/jdbc3/JDBC3Connection.java: /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/src/main/java/org/sqlite/jdbc3/JDBC3Connection.java uses unchecked or unsafe operations.
[WARNING] /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/src/main/java/org/sqlite/jdbc3/JDBC3Connection.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-bundle-plugin:2.4.0:manifest (default) @ sqlite-jdbc ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sqlite-jdbc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] skip non existing resourceDirectory /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ sqlite-jdbc ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ sqlite-jdbc ---
[INFO] Surefire report directory: /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.sqlite.UDFTest
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.287 sec
Running org.sqlite.TypeMapTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.sqlite.SQLiteConfigTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.sqlite.PrepStmtTest
Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 sec
Running org.sqlite.SavepointTest
running in native mode
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec
Running org.sqlite.ExtendedCommandTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.sqlite.TransactionTest
running in native mode
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.159 sec
Running org.sqlite.ExtensionTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running org.sqlite.SQLiteConnectionPoolDataSourceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.011 sec
Running org.sqlite.QueryTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec
Running org.sqlite.SQLiteJDBCLoaderTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.322 sec <<< FAILURE!
multipleClassLoader(org.sqlite.SQLiteJDBCLoaderTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Couldn't find classes under test.
        at org.junit.Assert.fail(Assert.java:89)
        at org.sqlite.SQLiteJDBCLoaderTest.multipleClassLoader(SQLiteJDBCLoaderTest.java:178)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.sqlite.SQLiteDataSourceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.sqlite.StatementTest
Tests run: 39, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.027 sec
Running org.sqlite.JDBCTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.sqlite.ReadUncommittedTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running org.sqlite.DBMetaDataTest
Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.055 sec
Running org.sqlite.ProgressHandlerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running org.sqlite.ConnectionTest
Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.274 sec
Running org.sqlite.BusyHandlerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.909 sec
Running org.sqlite.JSON1Test
Tests run: 57, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running org.sqlite.ErrorMessageTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec <<< FAILURE!
writeProtected(org.sqlite.ErrorMessageTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.AssertionError: Expected test to throw exception with message a string containing "[SQLITE_READONLY]"
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:278)
        at org.junit.rules.ExpectedException.access$100(ExpectedException.java:111)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:264)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.sqlite.FetchSizeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.sqlite.ListenerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.009 sec
Running org.sqlite.ResultSetTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
Running org.sqlite.util.OSInfoTest
Jul 15, 2021 3:37:02 PM org.sqlite.util.OSInfoTest testGetHardwareName
INFO: Hardware name: aarch64

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.058 sec
Running org.sqlite.BackupTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 sec
Running org.sqlite.RSMetaDataTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running org.sqlite.InsertQueryTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec

Results :

Failed tests:   multipleClassLoader(org.sqlite.SQLiteJDBCLoaderTest): Couldn't find classes under test.
  writeProtected(org.sqlite.ErrorMessageTest): Expected test to throw exception with message a string containing "[SQLITE_READONLY]"

Tests run: 307, Failures: 2, Errors: 0, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.083 s
[INFO] Finished at: 2021-07-15T15:37:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project sqlite-jdbc: There are test failures.
[ERROR]
[ERROR] Please refer to /home/stage/root/spack-stage-sqlite-jdbc-3.36.0.1-inxithh4wckpkeiflzuyh3eluyldblgm/spack-src/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make: *** [Makefile:54: test] Error 1
```
Can you help me analyze it?
### Information on your system
[root@localhost spack-src]#spack debug report
* **Spack:** 0.16.1
* **Python:** 3.7.9
* **Platform:** linux-openeuler20-aarch64
* **Concretizer:** original

**Comment by gotson** [comment]
Tests always fail as root, because there's some read only tests, but sqlite relies on the filesystem permissions for read-only access. Root always have write access, so read-only tests fail as root.

**Comment by gotson** [comment]
Multiple class loader test was fixed recently, it would fail if the directory was renamed. See #647

This issue should be closed.
