### ISSUE TITLE
Issue with Aggregate Functions - JNI ERROR (app bug): local reference table overflow (max=512)

### ISSUE THREAD

**Issue by utikawa** [xerial/sqlite-jdbc#643]
Hi!
I am facing an issue and was unable to solve it.
It seems that something is wrong with aggregate functions handling on sqlite-jdbc.
The error message is: JNI ERROR (app bug): local reference table overflow (max=512)
Complete stacktrace, query and code of functions are [here](https://drive.google.com/file/d/1pt-oRN2qXFUWpFwPgMGdov39cKUmESn4).
The query do a subquery to sum prices for a order. The complete query is:

```sql
select v.id                                                                                  as v_id,
       v.numero                                                                              as v_num,
       v.caminho                                                                             as v_cam,
       v.cancelado                                                                           as v_canc,
       v.numero_cancelado                                                                    as v_nCanc,
       v.caminho_cancelado                                                                   as v_cCanc,
       p.id                                                                                  as p_id,
       p.data_hora                                                                           as p_data_hora,
       p.cliente_nome                                                                        as p_cliente_nome,
       p.cliente_cpf_cnpj                                                                    as p_cliente_cpf_cnpj,
       p.numero_pedido                                                                       as p_num_ped,
       (select count(i.id) from item_produto i where i.pedido_id = p.id and i.cancelado = 0) as nItem,
       (select sum_abnt(calc_produto(item_produto.preco, item_produto.quantidade, item_produto.desc_acre_por,
                                     item_produto.acrescimo, item_produto.desconto, item_produto.rateio))
        from item_produto
        where item_produto.pedido_id = p.id
          and item_produto.cancelado = 0)                                                    as vSubTot,
       p.desconto                                                                            as descNoCupom,
       p.acrescimo                                                                           as acreNoCupom,
       p.desc_acre_por                                                                       as porcentagemNoCupom
from venda as v
         join pedido as p on v.pedido_id = p.id
where p.data_hora >= ?
  and p.data_hora <= ?
  and v.cancelado = 0
order by p.data_hora desc
```

parcial stackstrace:
```
08-16 10:17:04.239 16455-17936/com.app.mobox A/art: art/runtime/indirect_reference_table.cc:98] JNI ERROR (app bug): local reference table overflow (max=512)
08-16 10:17:04.239 16455-17936/com.app.mobox A/art: art/runtime/indirect_reference_table.cc:98] local reference table dump:
08-16 10:17:04.239 16455-17936/com.app.mobox A/art: art/runtime/indirect_reference_table.cc:98]   Summary:
08-16 10:17:04.239 16455-17936/com.app.mobox A/art: art/runtime/indirect_reference_table.cc:98]       512 of com.app.mobox.dao.swedadatabase.SumABNTRound_SQLFunction (512 unique instances)
08-16 10:17:04.239 16455-17936/com.app.mobox A/art: art/runtime/indirect_reference_table.cc:98] 
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289] Runtime aborting...
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   at java.lang.Object.clone(Object.java:172)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   at org.sqlite.Function$Aggregate.clone(Function.java:315)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   at org.sqlite.core.NativeDB.step(Native method)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   - locked <0x35b8ddc8> (a org.sqlite.core.NativeDB)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   at org.sqlite.core.DB.execute(DB.java:851)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   - locked <0x35b8ddc8> (a org.sqlite.core.NativeDB)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
08-16 10:17:07.268 16455-17936/com.app.mobox A/art: art/runtime/runtime.cc:289]   at app.sweda.utils.SwedaDataBase.SwedaDataBase.rawQuery(SwedaDataBase.java:231)
```

I think that the references to functions running on subquery are being held while the main query is running, causing an overflow.
Is there anything else I could provide for better understanding?
Thanks in advance.

**Comment by gotson** [comment]
Is this still an issue?

**Comment by gotson** [comment]
Closing this as no feedback was received.
