### ISSUE TITLE
Error creating sqlite connection

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#670]
version: 3.34.0

`
Caused by: java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.k2view.fabric.fabricdb.context.sqlite.SqliteMdb.<init>(SqliteMdb.java:52)
	... 14 common frames omitted
Caused by: java.lang.Exception: No native library found for os.name=Windows, os.arch=x86_64, paths=[/org/sqlite/native/Windows/x86_64;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.292-1\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\K2View\k2Admin\PHPEXE\;C:\K2View\k2Admin\SVN\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.292-1\bin;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.292-1\jre\bin;C:\K2View\k2Admin\OraClient11_64\;C:\K2View\k2Admin\PHP\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\K2View\k2Admin\PHPEXE\;C:\K2View\k2Admin\SVN\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.292-1\bin;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.292-1\jre\bin;C:\K2View\k2Admin\OraClient11_64\;C:\K2View\k2Admin\PHP\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;.]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:367)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:67)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
	... 22 common frames omitted
`

Failed to load native library:sqlite-3.34.0-48881293-4db6-4948-b4f5-25d5e93f7470-sqlitejdbc.dll. osinfo: Windows/x86_64
java.lang.UnsatisfiedLinkError: C:\Users\k2view\AppData\Local\Temp\9\sqlite-3.34.0-48881293-4db6-4948-b4f5-25d5e93f7470-sqlitejdbc.dll: The parameter is incorrect

**Comment by gotson** [comment]
There's not enough information to help you. Is this still a problem?

**Comment by mhanna** [comment]
No

I think the root cause was insufficient write permissions in the default temp folder path
