### ISSUE TITLE
Got "no such function: mod" when run query "SELECT MOD(9,4)" with version 3.36.0.3

### ISSUE THREAD

**Issue by seebigsea** [xerial/sqlite-jdbc#692]
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such function: mod)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)

**Comment by gotson** [comment]
Maybe linked to #633?

**Comment by gotson** [comment]
Closing this in favor of #633
