### ISSUE TITLE
java.lang.AbstractMethodError: Method org/sqlite/PrepStmt.isClosed()Z is abstract

### ISSUE THREAD

**Issue by Trqhxrd** [xerial/sqlite-jdbc#762]
I am running version 3.39.2.0 from the maven central and when I try to connect to a database I get this exception:
```
java.lang.AbstractMethodError: Method org/sqlite/PrepStmt.isClosed()Z is abstract
	at org.sqlite.PrepStmt.isClosed(PrepStmt.java) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.closeIfPossible(JdbcPreparedStatementImpl.kt:44) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.closeStatementsAndConnection(ThreadLocalTransactionManager.kt:247) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:209) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132) ~[?:?]
[...]
```

I tried relocating the `org.sqlite` package but that led to another exception:
```
java.lang.NoClassDefFoundError: org/sqlite/core/NativeDB
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817) ~[?:1.8.0_342]
	at java.lang.Runtime.load0(Runtime.java:810) ~[?:1.8.0_342]
	at java.lang.System.load(System.java:1088) ~[?:1.8.0_342]
	at me.trqhxrd.bedwars.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:296) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:253) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:366) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.core.NativeDB.load(NativeDB.java:61) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.SQLiteConnection.open(SQLiteConnection.java:254) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:60) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:23) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.JDBC.createConnection(JDBC.java:104) ~[?:?]
	at me.trqhxrd.bedwars.sqlite.JDBC.connect(JDBC.java:77) ~[?:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_342]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_342]
	at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:206) ~[?:?]
	at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:206) ~[?:?]
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:127) ~[?:?]
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:128) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:69) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:68) ~[?:?]
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:75) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt) ~[?:?]
	at org.jetbrains.exposed.sql.vendors.VendorDialect.tableExists(Default.kt:694) ~[?:?]
	at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:236) ~[?:?]
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:96) ~[?:?]
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:258) ~[?:?]
	at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:256) ~[?:?]
[...]
```

I already created a ticket over in the Exposed repo but to no avail. Any idea how to fix this?

**Comment by gotson** [comment]
> I already created a ticket over in the Exposed repo

Can you share that?

**Comment by Trqhxrd** [comment]
Sure thing: https://github.com/JetBrains/Exposed/issues/1559

They basically said that the driver I'm shading into my plugin is overriding part of another driver already included in the server.

**Comment by Trqhxrd** [comment]
So I just checked and there actually is a SQLite driver in there. But it still does not work even without your driver shaded into the jar. Any idea how I can relocate your driver without getting the `NoClassDefFoundError` from my opening comment?

**Comment by gotson** [comment]
Well to be honest that kind of question would fit better at stackoverflow.com. It's about shading jars, not the driver itself, and it depends on your build tool and project.
