### ISSUE TITLE
Can't find native library on Windows Server 2019 Standard OS (Polish region)

### ISSUE THREAD

**Issue by ed-erwin-tf** [xerial/sqlite-jdbc#791]
**Describe the bug**
Failing to open a connection to SQLite on Polish Windows **Server** 2019 Standard OS.

**To Reproduce**
Create a jdbc URL, then try to open a connection

    Connection conn = null;
    final SQLiteConfig config = new SQLiteConfig();
    config.setReadOnly(true);
    conn = java.sql.DriverManager.getConnection(jdbcUrl, config.toProperties());
    conn.open()

**Expected behavior**
Open a connection

**Logs**

    Caused by: java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:244)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.JDBC.connect(JDBC.java:90)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
        at com.affymetrix.chas.config.db.DBAppSettingsReader.getConnectionToSQLiteDB(DBAppSettingsReader.java:206)
        at com.affymetrix.chas.config.db.DBAppSettingsReader.getSQLiteDBConnection(DBAppSettingsReader.java:185)
        at com.affymetrix.chas.config.db.DBAppSettingsReader.getSettings(DBAppSettingsReader.java:76)
        ... 5 common frames omitted
    Caused by: java.lang.Exception: No native library found for os.name=Windows, os.arch=x86_64, paths=[/org/sqlite/native/Windows/x86_64;C:\Program Files\Affymetrix\ChASDx\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\affxuser\AppData\Local\Microsoft\WindowsApps;.]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:389)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:240)
        ... 15 common frames omitted

**Environment**
 - OS: Windows Server 2019 Standard, Polish region
 - CPU architecture: x86_64
 - sqlite-jdbc version 3.36.0.3

**Additional context**
This has been working correctly on Windows 10 set-up for multiple regions.
It is failing on Windows Server.  The fact that it is a Polish region may not be relevant.  Could just be problem with Windows Server in general.
The sqlite-jdbc-3.36.0.3.jar file does contain org.sqlite.native.Windows.x86_64/sqlitejdbc.dll

**Comment by ed-erwin-tf** [comment]
This problem is resolved.  The bug was with the machine itself.  After re-installing a Windows image, the problem disappeared.
