### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlitejdbc.so" not found on Android

### ISSUE THREAD

**Issue by jrjohn** [xerial/sqlite-jdbc#794]
TCL30XL Android 12
implementation 'org.xerial:sqlite-jdbc:3.39.3.0'

Same as issue #248 

2022-10-12 18:34:13.699 7957-7957/com.somnics.sqlite I/Create Android: os.name======>Linux
2022-10-12 18:34:13.699 7957-7957/com.somnics.sqlite I/Create Android: os.arch======>aarch64
2022-10-12 18:34:13.701 7957-7957/com.somnics.sqlite D/AndroidRuntime: Shutting down VM
2022-10-12 18:34:13.706 7957-7957/com.somnics.sqlite E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.somnics.sqlite, PID: 7957
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlitejdbc.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.somnics.sqlite.MainActivity.<clinit>(MainActivity.java:31)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1296)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3675)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3949)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)

**Comment by gotson** [comment]
please use the issue templates correctly
