### ISSUE TITLE
UUID column type not supported for reading

### ISSUE THREAD

**Issue by Timelessprod** [xerial/sqlite-jdbc#800]
**Describe the bug**
When loading a Sqlite `.db` file with pyspark and JDBC, if the table contain a column of type UUID, it will be wrongly parsed and makes the table unreadable at all.

**To Reproduce**
Create a `.db` file containing a table with a UUID column (content doesn't matter as long as it is alphanumeric).

Then run:
```py
import numpy as np
import matplotlib.pyplot as plt
import os

import findspark
findspark.init()

from pyspark.sql import SparkSession, DataFrame
from pyspark.conf import SparkConf
from pyspark.sql.types import StructType, StructField, StringType, FloatType, BooleanType, DateType, TimestampType, DecimalType

jdbc_jar_path = os.path.join(os.getcwd(), 'lib/sqlite-jdbc-3.39.3.0.jar')

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("Spark Task") \
    .config("spark.jars", jdbc_jar_path) \
    .getOrCreate()

from pyspark.sql import SQLContext
sqlContext = SQLContext(spark)

customer_schema = StructType([
    StructField('id', DecimalType(38,18), True)
])

customer_df = sqlContext.read \
    .format("jdbc") \
    .options(url = "jdbc:sqlite:data/customer.db", driver="org.sqlite.JDBC", dbtable="customer") \
    .schema(customer_schema) \
    .load()
```

This gave the following error :
```
java.sql.SQLException: Bad value for type BigDecimal : b39d5aec-ec64-43af-9d88-ee4e126329de
	at org.sqlite.jdbc3.JDBC3ResultSet.getBigDecimal(JDBC3ResultSet.java:176)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$makeGetter$3(JdbcUtils.scala:399)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$makeGetter$3$adapted(JdbcUtils.scala:397)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:348)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anon$1.getNext(JdbcUtils.scala:330)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I also tried to parse the column as a `StringType` : I get an error indicating I should use DecimalType instead. If I don't give a schema at all it will go on a DecimalType and fail too.

**Expected behavior**
The table should be correctly loaded using StringType (or DecimalType I don't know which one is the most accurate).

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS on Windows 10 x86_64 (WSL 2)
 - CPU architecture: Intel i7-10875H (16) @ 2.304GHz
 - sqlite-jdbc version: 3.39.3.0 (latest tag on this repository)

**Additional context**

**Comment by gotson** [comment]
Please try to provide a repro in a self contained unit test in plain Java.

**Comment by gotson** [comment]
Or can you at least share the `create table` instruction you used.

**Comment by gotson** [comment]
Closing this as no feedback was received.
