### ISSUE TITLE
UnsatisfiedLinkError (undefined symbol: trunc) With JDBC Driver 3.40.0.0

### ISSUE THREAD

**Issue by rkrier85233** [xerial/sqlite-jdbc#828]
**Describe the bug**
My JVM is running in a Docker container eclipse-temurin:8u322-b06-jdk (Linux/amd64).  When I make a connection an UnsatisfiedLinkError is thrown.  When I use JDBC driver version 3.39.4.1 or prior the error does not occur.  See stack trace below.

Note: at this time we cannot go to a higher Java version and we must use a JDK that supports TLSv1.3.

**To Reproduce**
- `docker pull eclipse-temurin:8u322-b06-jdk`
- Start the container and and open a command line.
- `cd ~`
- `curl https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.40.0.0/sqlite-jdbc-3.40.0.0.jar --output sqlite-jdbc-3.40.0.0.jar`
- Create and compile Test.java as shown below. `javac -cp sqlite-jdbc-3.40.0.0.jar Test.java`
-  Run the program:  `java -cp sqlite-jdbc-3.40.0.0.jar:. Test`

**Test.java**

```java
import java.sql.Connection;
import java.sql.DriverManager;

public class Test {

        public static void main(String[] args) throws Exception {
                Class.forName("org.sqlite.JDBC");

                try (Connection c = DriverManager.getConnection("jdbc:sqlite:demo.db")) {
                        System.out.println("Connection made!");

                }
        }
}
```

**Expected behavior**
It is expected to not throw an error but make the connection successfull.

**Logs**

```
Failed to load native library:sqlite-3.40.0.0-41636660-39ef-4741-8354-138add5edec0-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.40.0.0-41636660-39ef-4741-8354-138add5edec0-libsqlitejdbc.so (/tmp/sqlite-3.40.0.0-41636660-39ef-4741-8354-138add5edec0-libsqlitejdbc.so: undefined symbol: trunc)
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1472)
        at java.lang.System.load(System.java:599)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at Test.main(Test.java:9)
Exception in thread "main" java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at Test.main(Test.java:9)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/opt/java/openjdk/jre/lib/amd64/default:/opt/java/openjdk/jre/lib/amd64:/usr/lib64:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        ... 8 more
```

**Environment (please complete the following information):**
 - OS: Linux
 - CPU architecture: x86_64
 - sqlite-jdbc version 3.40.0.0

**Additional context**
I can reproduce this on `ibm-semeru-runtimes:open-8-jdk-focal` as well and possibly others.  
See recommended solution [here](https://sqlite.org/forum/forumpost/412d2b6675).

**Comment by gotson** [comment]
What is the underlying OS on which you run Docker ?

**Comment by gotson** [comment]
I can't reproduce on my side, it works as expected. I am running Docker 20.10.21 on macOS.

**Comment by rkrier85233** [comment]
My underlying OS is 
![image](https://user-images.githubusercontent.com/871468/212237762-4a7ba70c-bd56-465e-9760-c44f393d49ab.png)

**Comment by rkrier85233** [comment]
Turns out I can't reproduce this either using the example I've given.  I thought for sure I could but I must have been confused.  It does happen in our Eclipse OSGI workspace but I'll try to investigate that further.  You can close this issue.
