### ISSUE TITLE
Binaries form armv5 are linked to GLIBC_2.34

### ISSUE THREAD

**Issue by wassinki** [xerial/sqlite-jdbc#890]
**Describe the bug**
The binaries for armv5 are linked to specific version form glibc 2.34. This is not the case for armv7 (using same glibc version).

**To Reproduce**
Upload the newest jars for 3.39.x and higher to a system with armv5.

**Expected behavior**
Dynamically linke to glibc without version dependency.

**Logs**
 java.lang.UnsatisfiedLinkError: /var/volatile/tmp/sqlite-3.39.4.1-40cddf51-24db-4af0-99ad-f5dcc244d1d8-libsqlitejdbc.so: /lib/libc.so.6: version `GLIBC_2.34' not found (required by /var/volatile/tmp/sqlite-3.39.4.1-40cddf51-24db-4af0-99ad-f5dcc244d1d8-libsqlitejdbc.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:63)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)

**Environment (please complete the following information):**
 - OS: Linux
 - CPU architecture: ArmV5
 - sqlite-jdbc version [e.g. 3.39.3.0 and higher]

**Comment by wassinki** [comment]
Thanks for the quick reply :)

I also tries [3.41.2.1](https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc/3.41.2.1). 

I think it has to do with the docker container version that is being used (latest). What I did was using an older docker container that had an older glibc version (I guess it works with newer). I am not a c expert, so I don't know how the linking exactly works. 

Some background information:
We have a yocto project that build linux versions for Armv7 and Armv5 (same source, different binaries). The armv7 works, but the armv5 not. I guess it has to do with the docker container for Armv7 is updated 9 months ago, and the Armv5 one is updated 7 months ago, and perhaps will use a newer glibc version.

**Comment by gotson** [comment]
What is the version of glibc on your host?

**Comment by wassinki** [comment]
That is the 2.33.

**Comment by gotson** [comment]
There's your problem then 😜

**Comment by wassinki** [comment]
Haha, yes :)

**Comment by wassinki** [comment]
Is it possible to set the docker container to a fixed version? Or do you see some problems for other installations?

**Comment by gotson** [comment]
Dockcross has made some lts versions of their containers to keep a lower glibc like 2.28.

You could always ask them for a lts version of armv5, but I have no idea how much work it is for them to maintain that.

Arm32 is dying slowly, support will dwindle.

**Comment by gotson** [comment]
Your use case is quite specific, if you really need sqlite-jdbc 3.39+ you can consider building the native lib yourself and loading it instesstof the bundled one.
