### ISSUE TITLE
No dynamic symbols when building with `make native` ppc64le

### ISSUE THREAD

**Issue by andreas-ibm** [xerial/sqlite-jdbc#903]
**Describe the bug**
When rebuilding the native library (in this case on ppc64le) the library can't be loaded because the embedded `libsqlitejdbc.so` doesn't export the symbol `Java_org_sqlite_core_NativeDB__1open_1utf8`.

**To Reproduce**
```
make native
nm -D  target/sqlite-3.41.2-Linux-ppc64/libsqlitejdbc.so | grep org_sqlite
```
gives no output

**Expected behavior**
expected 59 entrypoints to be exported so they can be `dlsym`ed from java.

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
 - OS: Linux
 - CPU architecture: ppc64le
 - sqlite-jdbc version 3.41.2.1

**Fix**
Change `Makefile.common`
from:
```
Linux-ppc64_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -Os -fPIC -fvisibility=hidden

```
to
```
Linux-ppc64_CCFLAGS   := -I$(JAVA_HOME)/include -Ilib/inc_linux -Os -fPIC -rdynamic
```

My question is; how was this meant to work, I see the same flags used on other platforms and they (presumably) work, so why not on ppc64?

I'll try s390x next :-)

**Comment by gotson** [comment]
Hi, CI tests are passing for ppc64le though https://github.com/xerial/sqlite-jdbc/actions/runs/4986892506/jobs/8928297470

Can you provide the logs of the library not loading ? You mention it, but don't provide any details.

**Comment by gotson** [comment]
Just tried on my machine:

```
> nm -D src/main/resources/org/sqlite/native/Linux/ppc64/libsqlitejdbc.so | grep org_sqlite
0000000000012080 T Java_org_sqlite_core_NativeDB__1close
000000000001008c T Java_org_sqlite_core_NativeDB__1exec_1utf8
000000000000fcc8 T Java_org_sqlite_core_NativeDB__1open_1utf8
0000000000011ac8 T Java_org_sqlite_core_NativeDB_backup
0000000000010c04 T Java_org_sqlite_core_NativeDB_bind_1blob
0000000000010b20 T Java_org_sqlite_core_NativeDB_bind_1double
0000000000010a60 T Java_org_sqlite_core_NativeDB_bind_1int
0000000000010ac0 T Java_org_sqlite_core_NativeDB_bind_1long
0000000000010a08 T Java_org_sqlite_core_NativeDB_bind_1null
0000000000010434 T Java_org_sqlite_core_NativeDB_bind_1parameter_1count
0000000000010b78 T Java_org_sqlite_core_NativeDB_bind_1text_1utf8
000000000000ffbc T Java_org_sqlite_core_NativeDB_busy_1handler
000000000000fe24 T Java_org_sqlite_core_NativeDB_busy_1timeout
000000000001023c T Java_org_sqlite_core_NativeDB_changes
00000000000103e0 T Java_org_sqlite_core_NativeDB_clear_1bindings
0000000000011dcc T Java_org_sqlite_core_NativeDB_clear_1progress_1handler
00000000000107ac T Java_org_sqlite_core_NativeDB_column_1blob
0000000000010488 T Java_org_sqlite_core_NativeDB_column_1count
0000000000010534 T Java_org_sqlite_core_NativeDB_column_1decltype_1utf8
0000000000010908 T Java_org_sqlite_core_NativeDB_column_1double
00000000000109b0 T Java_org_sqlite_core_NativeDB_column_1int
000000000001095c T Java_org_sqlite_core_NativeDB_column_1long
0000000000011730 T Java_org_sqlite_core_NativeDB_column_1metadata
0000000000010644 T Java_org_sqlite_core_NativeDB_column_1name_1utf8
00000000000105bc T Java_org_sqlite_core_NativeDB_column_1table_1name_1utf8
00000000000106cc T Java_org_sqlite_core_NativeDB_column_1text_1utf8
00000000000104dc T Java_org_sqlite_core_NativeDB_column_1type
000000000001153c T Java_org_sqlite_core_NativeDB_create_1collation_1utf8
00000000000112c8 T Java_org_sqlite_core_NativeDB_create_1function_1utf8
000000000001163c T Java_org_sqlite_core_NativeDB_destroy_1collation_1utf8
00000000000114a0 T Java_org_sqlite_core_NativeDB_destroy_1function_1utf8
000000000000fc60 T Java_org_sqlite_core_NativeDB_enable_1load_1extension
0000000000010150 T Java_org_sqlite_core_NativeDB_errmsg_1utf8
00000000000102e4 T Java_org_sqlite_core_NativeDB_finalize
000000000000fdc8 T Java_org_sqlite_core_NativeDB_interrupt
00000000000101d8 T Java_org_sqlite_core_NativeDB_libversion_1utf8
00000000000116cc T Java_org_sqlite_core_NativeDB_limit
000000000000ffd4 T Java_org_sqlite_core_NativeDB_prepare_1utf8
0000000000011da8 T Java_org_sqlite_core_NativeDB_register_1progress_1handler
000000000001038c T Java_org_sqlite_core_NativeDB_reset
0000000000011c38 T Java_org_sqlite_core_NativeDB_restore
0000000000010de0 T Java_org_sqlite_core_NativeDB_result_1blob
0000000000010ee4 T Java_org_sqlite_core_NativeDB_result_1double
0000000000010fac T Java_org_sqlite_core_NativeDB_result_1error_1utf8
0000000000010f68 T Java_org_sqlite_core_NativeDB_result_1int
0000000000010f24 T Java_org_sqlite_core_NativeDB_result_1long
0000000000010cf4 T Java_org_sqlite_core_NativeDB_result_1null
0000000000010d34 T Java_org_sqlite_core_NativeDB_result_1text_1utf8
0000000000011f58 T Java_org_sqlite_core_NativeDB_set_1commit_1listener
0000000000011dec T Java_org_sqlite_core_NativeDB_set_1update_1listener
000000000000fc20 T Java_org_sqlite_core_NativeDB_shared_1cache
0000000000010338 T Java_org_sqlite_core_NativeDB_step
0000000000010290 T Java_org_sqlite_core_NativeDB_total_1changes
00000000000110bc T Java_org_sqlite_core_NativeDB_value_1blob
0000000000011188 T Java_org_sqlite_core_NativeDB_value_1double
000000000001122c T Java_org_sqlite_core_NativeDB_value_1int
00000000000111d8 T Java_org_sqlite_core_NativeDB_value_1long
000000000001103c T Java_org_sqlite_core_NativeDB_value_1text_1utf8
0000000000011284 T Java_org_sqlite_core_NativeDB_value_1type
```

**Comment by gotson** [comment]
Just so i understand, the issue is when you recompile using `make native` on a ppc64 machine, it is not a problem with the bundled library, is it?

**Comment by andreas-ibm** [comment]
Sorry for not including initial logs!
Yes the built-in library fails for me:
```
java -classpath .:/root/sqlite-jdbc-3.41.2.1.jar Sample
Failed to load native library:sqlite-3.41.2.1-6879d4f3-7d73-4489-af2c-2f187725cab0-libsqlitejdbc.so. osinfo: Linux/ppc64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.41.2.1-6879d4f3-7d73-4489-af2c-2f187725cab0-libsqlitejdbc.so (/lib64/libm.so.6: version `GLIBC_2.29' not found (required by
/tmp/sqlite-3.41.2.1-6879d4f3-7d73-4489-af2c-2f187725cab0-libsqlitejdbc.so))
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1460)
        at java.lang.System.load(System.java:590)
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)
        at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:279)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:66)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.JDBC.connect(JDBC.java:77)
        at java.sql.DriverManager.getConnection(DriverManager.java:675)
        at java.sql.DriverManager.getConnection(DriverManager.java:281)
        at Sample.main(Sample.java:15)
Error opening connection
```
I'm on:
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)
$ uname -r
4.18.0-425.19.2.el8_7.ppc64le
```
checking the built-in lib:
```
$ nm -D ./org/sqlite/native/Linux/ppc64/libsqlitejdbc.so | grep org_sqlite | wc -l
59
```
so the shipped lib does indeed contain everything, it's just a little too new!
```
$ nm --with-symbol-versions -D /lib64/libm.so.6 | cut -d@ -f3 | sort -u

GLIBC_2.17
GLIBC_2.18
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
```

I therefore tried rebuilding it, and hit the above problems. Now I *suspect* this may actually be a difference/quirk in the linker as it behaves slightly differently on x than p.

thanks!

**Comment by gotson** [comment]
We build using dockcross, glibc 2.29 is more than 4y old already.

You could either update your base os, or use an older version of sqlite-jdbc, or indeed recompile by yourself, but in this case it's up to you to make it work for your specific system.

`make native` is provided as a convenience, because we don't use it anymore to build the bundled libs, as everything is built via docker.

**Comment by andreas-ibm** [comment]
Ah, that makes sense, thanks.
Would you accept PRs to the Makefile? I have a section to make it build on AIX now, and have stood up a zLinux machine to test it there too.
I'll have to have a play with `dockcross`, that's a new one to me.

**Comment by gotson** [comment]
> Would you accept PRs to the Makefile? I have a section to make it build on AIX now, and have stood up a zLinux machine to test it there too.

we don't support those arch, so any change would only be relevant for people building by themselves. Maybe you can point to the changes in your fork, and i can tell you whether we would be interested in a PR or not.
