### ISSUE TITLE
Sqlite-jdbc native driver for armv5tejl

### ISSUE THREAD

**Issue by ricardogarfe** [xerial/sqlite-jdbc#94]
Hi! we need to use the driver into _armv5tejl_ that is not included for compilation:

``` shell
# for cross-compilation on Ubuntu, install the g++-arm-linux-gnueabi package
linux-arm:
    $(MAKE) native CROSS_PREFIX=arm-linux-gnueabi- OS_NAME=Linux OS_ARCH=arm

# for cross-compilation on Ubuntu, install the g++-arm-linux-gnueabihf package
linux-armhf:
    $(MAKE) native CROSS_PREFIX=arm-linux-gnueabihf- OS_NAME=Linux OS_ARCH=armhf
```

Thus when we launch the application we recieve this error:

``` shell
Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=arm
    at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:284)
    at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
    at org.sqlite.core.NativeDB.load(NativeDB.java:53)
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:136)
```

Is there any chance to package the library or workaround to use with this architecture ?

``` shell
arietta:~# uname -a
Linux arietta 4.2.6 #1 Fri Nov 20 12:57:40 CET 2015 armv5tejl GNU/Linux
```
## Sqlite-jdbc

Driver version `sqlite-jdbc-3.8.11.2.jar`.
## OpenJDK

```
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1~deb8u1)
OpenJDK Zero VM (build 24.91-b01, mixed mode)
```
## Sample

Using sample tutorial from README.md we have same error.

**Comment by xerial** [comment]
@ricardogarfe Could you try the latest version? I recompiled native libraries for arm.

**Comment by xerial** [comment]
Let me close it due to inactivities.

**Comment by ricardogarfe** [comment]
Sorry for the delayed answer, but now I not in this project I could reach the other mates to test it,
Thanks a lot for everything!
