### ISSUE TITLE
Support for Debian aarch64

### ISSUE THREAD

**Issue by artemptushkin** [xerial/sqlite-jdbc#943]
I have an error running the driver on my raspberry pi 4 in Docker, here are the details:

* org.xerial:sqlite-jdbc:3.40.1.0
* the image is built on the rasbperrypi itself
* arch print
```
$ lscpu

Architecture:                    aarch64
Vendor ID:                       ARM

```
* the error
Summary:
```
No native library found for os.name=Linux, os.arch=aarch64

Caused by: java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open_utf8(byte[], int)'
```
* Detailed error
```
Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: 'void org.sqlite.core.NativeDB._open_utf8(byte[], int)'
	...
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[spring-boot-3.1.0.jar:3.1.0]
	...
Caused by: java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open_utf8(byte[], int)'
	at org.sqlite.core.NativeDB._open_utf8(Native Method) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.core.NativeDB._open(NativeDB.java:79) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.core.DB.open(DB.java:216) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:285) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.JDBC.createConnection(JDBC.java:104) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.JDBC.connect(JDBC.java:77) ~[sqlite-jdbc-3.40.1.0.jar:na]
```

Another one:
```
java.sql.SQLException: Error opening connection
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.JDBC.createConnection(JDBC.java:104) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.JDBC.connect(JDBC.java:77) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:316) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	...
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/usr/java/packages/lib:/lib:/usr/lib]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.core.NativeDB.load(NativeDB.java:67) ~[sqlite-jdbc-3.40.1.0.jar:na]
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278) ~[sqlite-jdbc-3.40.1.0.jar:na]
	... 49 common frames omitted
```

How can I fix it? If it needs a fix, could you recommend a workaround if possible until then?

**Comment by jerryma0912** [comment]
Yes, I had the same problem, how did you solve it?

**Comment by artemptushkin** [comment]
@gotson I have `os.arch=aarch64` when I `lscpu` on the raspberry pi host and I have the same in the docker container, it's not arm32

when I `docker info`: `Architecture: aarch64`

I'm confused, I installed 32 as I remember and I have to set explicitly architecture to `arm` when building the image or Java doesn't work..

**Comment by artemptushkin** [comment]
```
# ls -la
total 24
drwxrwxrwt 1 root root 4096 Aug  3 12:16 .
drwxr-xr-x 1 root root 4096 Aug  3 12:16 ..
drwxr-xr-x 1 root root 4096 Aug  3 12:16 hsperfdata_root
drwx------ 3 root root 4096 Aug  3 12:16 tomcat.8080.12494996071690896671
drwx------ 2 root root 4096 Aug  3 12:16 tomcat-docbase.8080.16656598209590538811
```

Yes I do have `tmp` in the root

**Comment by artemptushkin** [comment]
Okay, but it doesn't have `org.sqlite.lib.name` the lib you expect according to the code, what guarantees that it's there?

**Comment by artemptushkin** [comment]
Okay, now I see

> sqlite-jdbc extracts a native library for your OS to the directory specified by java.io.tmpdir JVM property. To use another directory, set org.sqlite.tmpdir JVM property to your favorite path.

but what guarantees that it really extracts? when it happens?

**Comment by artemptushkin** [comment]
@gotson you were right, here is the linux issue https://github.com/raspberrypi/linux/issues/5402

@jerryma0912  I fixed this with setting `arm_64bit=0` to `/boot/config.txt`
