### ISSUE TITLE
Android API 22 and below throws `UnsatisfiedLinkError`

### ISSUE THREAD

**Issue by 05nelsonm** [xerial/sqlite-jdbc#961]
**Describe the bug**
Android API 22 and below throws an error because `__register_atfork` is not available.

See: [https://android.googlesource.com/...](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#available-in-api-level-23)

**To Reproduce**
1. Extract binaries to `jniLibs` directory
2. Call `JDBC.isValidUrl(null) // Android API 23 and below does not automatically load services, so need to proc registration by referencing JDBC before creating a connection`
3. Run tests on Android API 22 or below

**Expected behavior**
Should not throw exception

**Logs**
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/io.toxicity.core.data.cipher.driver.test.test-1/lib/x86_64/libsqlitejdbc.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:371)
at java.lang.System.loadLibrary(System.java:989)
at org.sqlite.core.NativeDB.<clinit>(NativeDB.java:44)
at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
at org.sqlite.JDBC.createConnection(JDBC.java:104)
at org.sqlite.JDBC.connect(JDBC.java:77)
at java.sql.DriverManager.getConnection(DriverManager.java:179)
```

**Environment (please complete the following information):**
 - OS: `Android (Emulator API 21, 22)`
 - CPU architecture: `x86`
 - sqlite-jdbc version:  `3.43.0.0`

**Additional context**
Unsure of the amount of engineering effort it would take to resolve this in order to support Android APIs 22 and below, but still good to know that minSdk is `23` for us android users.

**Comment by 05nelsonm** [comment]
> We would need some help to understand what's needed to fix this.

Wish I was more versed with the native and JNI side of things, but unfortunately I am unable to assist :cry:

**Comment by gotson** [comment]
I'm not very familiar with Android API levels but 23 seems to be Android 6.0. Is there really a need to support older android versions ?

**Comment by gotson** [comment]
Just taken from the New Project Wizard in Android Studio:
<img width="544" alt="image" src="https://github.com/xerial/sqlite-jdbc/assets/2139133/5da41000-1605-477c-ab44-65b1a550e4c6">

**Comment by gotson** [comment]
We use Dockcross to compile the Android binaries, and it seems they only support API level 23: https://github.com/dockcross/dockcross/blob/85db3452be297dacec9f98dc1832801212254395/android-arm/Dockerfile.in#L21

Nothing we can do on our side unfortunately.
