### ISSUE TITLE
org.hibernate.exception.GenericJDBCException: Unable to extract generated-keys ResultSet

### ISSUE THREAD

**Issue by McBluna** [xerial/sqlite-jdbc#963]
**Describe the bug**
While my application is trying to save the first entity to sqlite dabase, the exception occurs. Never happened before, and this was the only change in my latest build. After switching back to 3.42.0.1 it's working again.

**To Reproduce**
Sorry, but I have no idea

**Expected behavior**
3.43.0.0 should behave like 3.42.0.1 😉

**Logs**
```
2023-08-30 20:30:03,537 ALL  : org.hibernate.exception.GenericJDBCException: Unable to extract generated-keys ResultSet [not implemented by SQLite JDBC driver] [insert into "CAST_INFO" ("D_ID","ADULT","BELONG","CAST_ID","CHARACTER","CREDIT_ID","DATA_TYPE","GENDER","LOAD","NAME","_order","PROFILE_PATH","TMDB_ID") values (?,?,?,?,?,?,?,?,?,?,?,?,?)]
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:61)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.id.insert.GetGeneratedKeysDelegate.performInsert(GetGeneratedKeysDelegate.java:139)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorPostInsertSingleTable.execute(MutationExecutorPostInsertSingleTable.java:101)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.persister.entity.mutation.InsertCoordinator.doStaticInserts(InsertCoordinator.java:169)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.persister.entity.mutation.InsertCoordinator.coordinateInsert(InsertCoordinator.java:111)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2757)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:674)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:291)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:272)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:322)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:363)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:277)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:180)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:140)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:175)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:93)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:77)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:54)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:755)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:739)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.hibernate.v4243.CastInfoDAO.save(CastInfoDAO.java:40)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.db.DBFactoryV4243.save(DBFactoryV4243.java:490)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.HomeTheaterDB.save(HomeTheaterDB.java:1487)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.lambda$createCastInfo$1(NFO.java:226)
2023-08-30 20:30:03,537 ALL  : 	at java.base/java.util.ArrayList.forEach(Unknown Source)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.createCastInfo(NFO.java:219)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.updateMovieInfo(NFO.java:643)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.processMovie(NFO.java:1327)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.insertMovie(NFO.java:1257)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.lambda$call$9(NFO.java:1661)
2023-08-30 20:30:03,537 ALL  : 	at java.base/java.lang.Iterable.forEach(Unknown Source)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.NFO.call(NFO.java:1642)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.config.NfoCommand.call(NfoCommand.java:470)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.config.NfoCommand.call(NfoCommand.java:25)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine.access$1500(CommandLine.java:148)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2023-08-30 20:30:03,537 ALL  : 	at picocli.CommandLine.execute(CommandLine.java:2170)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.HomeTheater.execute(HomeTheater.java:93)
2023-08-30 20:30:03,537 ALL  : 	at net.mcbluna.zidoo.HomeTheater.main(HomeTheater.java:138)
2023-08-30 20:30:03,537 ALL  : Caused by: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
2023-08-30 20:30:03,537 ALL  : 	at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448)
2023-08-30 20:30:03,537 ALL  : 	at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)
2023-08-30 20:30:03,537 ALL  : 	at org.hibernate.id.insert.GetGeneratedKeysDelegate.performInsert(GetGeneratedKeysDelegate.java:110)
2023-08-30 20:30:03,537 ALL  : 	... 44 more
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - CPU architecture: x86_64
 - sqlite-jdbc version 3.43.0.0

**Additional context**
My application is updating a SQLite database from an Android based media player.

**Comment by McBluna** [comment]
Oh, maybe I should have read the release log for 3.43.0.0 before 🤦‍♂️

🚨 remove support for Statement#getGeneratedKeys: getGeneratedKeys is not supported anymore

Any suggestion what I've to change in my code to not use getGeneratedKeys?

**Comment by McBluna** [comment]
From what I see, I've to change how hibernates handles the `getGeneratedKeys` stuff.
My code uses persist on session to save entity.

	public void save(final CastInfo transientInstance) {
		if (LOG.isDebugEnabled()) {
			LOG.debug("saving CastInfo instance");
		}
		try {
			getSession().**persist**(transientInstance);
			if (LOG.isDebugEnabled()) {
				LOG.debug("save successful");
			}
		} catch (final RuntimeException re) {
			if (LOG.isErrorEnabled()) {
				LOG.error("save failed", re);
			}
			throw re;
		}
	}

**Comment by gotson** [comment]
> Any suggestion what I've to change in my code to not use getGeneratedKeys?

You should use https://www.sqlite.org/lang_returning.html

**Comment by sproket** [comment]
Is the returning clause supported on older releases of sqlite?

**Comment by McBluna** [comment]
It is supported until version 3.42.0.1.

**Comment by gotson** [comment]
> Is the returning clause supported on older releases of sqlite?

> The RETURNING syntax has been supported by SQLite since version 3.35.0 (2021-03-12).

**Comment by prrvchr** [comment]
@McBluna  You can try this version: [SQLite-jdbc-3.45.1.3-SNAPSHOT.jar](https://github.com/prrvchr/sqlite-jdbc/releases/download/3.45.1.3-SNAPSHOT/sqlite-jdbc-3.45.1.3-SNAPSHOT.jar) normally it is full compatible with JDBC 4.1and therefore able to recover the primary keys via JDBC.
