### ISSUE TITLE
Sqlite 3.43.2.0 Breaks Local Gradle Dependency Usage

### ISSUE THREAD

**Issue by austinarbor** [xerial/sqlite-jdbc#994]
**Describe the bug**
In 3.43.2.0, a breaking change was added that no longer allows `sqlite-jdbc` to be used as a local file dependency when using gradle

**To Reproduce**
Create a gradle project with the structure
```
build.gradle.kts
libs/sqlite-jdbc-3.43.0.0.jar
libs/sqlite-jdbc-3.43.2.0.jar
src/test/kotlin/com/example/MyTest.kt
```

`build.gradle.kts`
```kotlin
plugins {
    java
    kotlin("jvm") version "1.9.10"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(files("libs/sqlite-jdbc-3.43.2.0.jar")) // does not work
    // implementation(files("libs/sqlite-jdbc-3.43.0.0.jar")) // works
    // implementation("org.xerial:sqlite-jdbc:3.43.2.0") // works
    // implementation("org.xerial:sqlite-jdbc:3.43.0.0") // works

    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.assertj:assertj-core:3.24.2")
}

kotlin {
    jvmToolchain(17)
}


tasks.named<Test>("test") {
    useJUnitPlatform()
}
```

`MyTest.kt`
```kotlin
@Test
    fun testCreateTable() {
        val (conn, stmt) = getConnectionAndStatement()
        conn.use { _ ->
            stmt.use { stmt ->
                val select = """
                    SELECT * FROM test;
                    """
                stmt.execute(select);
            }
        }
    }

@Throws(SQLException::class)
    private fun getConnectionAndStatement(): Pair<Connection, Statement> {
        val conn = DriverManager.getConnection("jdbc:sqlite::memory:")
        val stmt = conn.createStatement()
        createTable(stmt)
        return conn to stmt
    }

    @Throws(SQLException::class)
    private fun createTable(stmt: Statement) {
        val create = """
            CREATE TABLE test(a TEXT, b TEXT);
            """
        stmt.execute(create)
    }
```

When running the test, this throws the exception
```shell
java.sql.SQLException: No suitable driver found for jdbc:sqlite::memory:
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
```

In `build.gradle.kts`, comment out 
```
implementation(files("libs/sqlite-jdbc-3.43.2.0.jar"))
```
and uncomment the line below. Rerun the test and note that everything succeeds. You can also verify that everything works as expected when using the dependency from maven central.

**Environment (please complete the following information):**
 - OS: Mac OS 13.4.1
 - CPU architecture: arm64
 - sqlite-jdbc version 3.42.2.0

I've attached a sample project to run. Just download the relevant jars from maven central and place in the `libs` directory

[sqlite-test.zip](https://github.com/xerial/sqlite-jdbc/files/12923925/sqlite-test.zip)

**Comment by gotson** [comment]
You need SLF4j as a dependency of sqlite-jdbc

**Comment by austinarbor** [comment]
@gotson that's working now, thanks for the help
